### ISSUE TITLE
Deleting an open file results in crash

### ISSUE THREAD

**Issue by johnnovak** [kyazdani42/nvim-tree.lua#413] opened 2021-05-30 10:40 UTC
1. Open the browser and press enter on some file to open it.
2. Switch back to the open browser and delete the file.
3. Vim will crash and exit 100% of the time.

**Comment by cloggier** [comment] 2021-05-30 16:45
Are you sure it's an actual crash? Perhaps you have it set to quit automatically when tree is the last buffer and while deleting file tree closes the buffer, closing the window then quits nvim because no other windows are open but tree's. ￼

**Comment by sindrets** [comment] 2021-05-30 17:31
This is not a crash unless you see some sort of message like "Segmentation fault (core dumped)". I assume this is happening because you have `g:nvim_tree_auto_close` enabled, and nvim-tree and the buffer of the file you are deleting are the only open windows. This was at least the only way I could reproduce this.
It's default vim behavior to close a buffer's window when you delete the buffer.

**Comment by johnnovak** [comment] 2021-05-30 23:58
Ah, you were right guys, it was `g:nvim_tree_auto_close` all along. Didn't occur to me that that could cause this behaviour. The lack of "Segmentation fault" should have given me a tip, good point. Closing.

**Closed** 2021-05-30 23:58 UTC

**Comment by delfick** [comment] 2022-03-07 09:42
Is there a way to have g:nvim_tree_auto_close and when you delete the currently open file it replaces that file with an empty buffer rather than closing all of vim? or go to one of the files that's previously been opened?

**Comment by kyazdani42** [comment] 2022-03-07 19:13
don't think so, but this wouldn't be too hard to implement i think if you wish to give it a go

**Comment by delfick** [comment] 2022-03-07 21:30
oh yeah. Are you able to point me at where to start looking please?

**Comment by kyazdani42** [comment] 2022-03-07 21:34
take a look at the auto_close implementation, maybe replacing it to check buffers instead of windows. Try that on your config this might not need to land in nvim-tree :)

**Comment by delfick** [comment] 2022-03-07 21:39
ah yeah, when I find time I'll start there. thanks :)

**Comment by alex-courtis** [comment] 2022-03-07 21:51
[Diagnostic Logging](https://github.com/kyazdani42/nvim-tree.lua#diagnostic-logging) has recently been added. You may find it helpful in your investigations.

Set `log.enable` and `log.types.all` and you can add e.g.
```lua
  log.line("delfick", "running job with timeout %dms", self.timeout)
```

**Comment by delfick** [comment] 2022-04-22 23:41
I never got around to looking into this cause I've spent most this year unwell (not covid). But it seems after a recent update it doesn't break anymore :)

**Comment by kyazdani42** [comment] 2022-04-23 08:57
hope you're feeling better then :)
