### ISSUE TITLE
Not able to close nvim-tree

### ISSUE THREAD

**Issue by jahn-mtg** [kyazdani42/nvim-tree.lua#357] opened 2021-04-29 17:31 UTC
I run `:NvimTreeToggle` and it opens. I run the command again it does not close. It instead returns 
`E5108: Error executing lua ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:235: attempt to call field 'nvim_win_hide' (a nil value)`

**Comment by sindrets** [comment] 2021-04-29 17:50
Duplicate of #305. Update neovim.

**Closed** 2021-05-17 20:00 UTC
