### ISSUE TITLE
"nvim_win_close"

### ISSUE THREAD

**Issue by JoaoVitorMendes** [kyazdani42/nvim-tree.lua#1526] opened 2022-08-20 20:48 UTC
### Description

I'm having trouble closing the same
:NvimTreeToggle
:NvimTreeClose

### Neovim version

```text
NVIM version v0.7.2
```

### Operating system and version

Linux 5.19.2-arch1-1

### nvim-tree version

https://github.com/kyazdani42/nvim-tree.lua

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]                                                                     
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

:NvimTreeToggle
:NvimTreeToggle << error

or use
after open
:NvTreeClose << erro
![Uploading 20220820_17h32m28s_grim.png…]()

### Actual behavior

:NvimTreeClose

i hope he closes

**Comment by alex-courtis** [comment] 2022-08-21 00:25
Could not reproduce with 0.7.2.

I had to add `local package_root = "/tmp/nvt-min/site/pack"` before line 3 of nvt-min.lua as it was missing.

Was an error shown when closing? The image link points back to this issue...

**Comment by JoaoVitorMendes** [comment] 2022-08-21 12:09
Hello, I add in which file?
`/tmp/nvt-min/site/pack"`
because`/tmp/nvt...`
there is no directory
If I use nvim version >= 8 can I use it without errors?

**Comment by alex-courtis** [comment] 2022-08-22 02:06
> Hello, I add in which file? `/tmp/nvt-min/site/pack"` because`/tmp/nvt...` there is no directory If I use neovim version >= 8 can I use it without errors?

I don't understand. The line was simply missing from `nvt-min.lua` and I added it back.

Please advise the actual error you are experiencing. The screenshot above is a broken link.

**Comment by JoaoVitorMendes** [comment] 2022-08-22 19:51
Hello, Strangely after I installed my system I didn't have any problems with :NvimTreeToggle

Thank you from the bottom of my heart for taking the time to fix my problems <3

**Comment by alex-courtis** [comment] 2022-08-22 23:14
> Hello, Strangely after I installed my system I didn't have any problems with :NvimTreeToggle

I suspect there may have been an old version of nvim-tree lurking in a directory on &rtp

**Closed by alex-courtis** 2022-08-22 23:14 UTC
Labels: bug, awaiting feedback
