### ISSUE TITLE
Redundant split with g:lua_tree_auto_open = 1?

### ISSUE THREAD

**Issue by huyvohcmc** [kyazdani42/nvim-tree.lua#136] opened 2020-11-21 11:53 UTC
When I set g:lua_tree_auto_open = 1 and open nvim with `nvim .`, I got this:

<img width="1440" alt="Screen Shot 2020-11-21 at 6 18 38 PM" src="https://user-images.githubusercontent.com/17645203/99876011-8b288500-2c26-11eb-9fb1-2dd8ced985da.png">

The cursor is in the left split, so when I close it I still have an empty spit (on the right) open. My expectation is that if I open `nvim .` and then `:q` I should be able to quit right away but instead, I need to `:q` 2 times.

Also one other thing: because when open nvim the cursor is in the left split and I choose to open a file via let's say fzf search, then the file will be open in the left split and keep the open split untouched:

<img width="1440" alt="Screen Shot 2020-11-21 at 6 52 11 PM" src="https://user-images.githubusercontent.com/17645203/99876644-ad240680-2c2a-11eb-9444-3123c245d761.png">

Maybe I've been so familiar with vim-dirvish, but do we have an option to only have 1 split (nvim-tree) when g:lua_tree_auto_open = 1?

**Comment by kyazdani42** [comment] 2020-11-21 12:04
This is intended behavior for both. Basically there will be an easy workaround for the next version, but in the meantime:
```vim
au FileType LuaTree lua vim.api.nvim_buf_set_keymap(0, 'n', '<C-p>', 'wincmd L :Files<CR>', {})
```

**Comment by ttys3** [comment] 2020-12-14 14:06
I got this problem too

**Comment by kyazdani42** [comment] 2021-06-02 17:25
i think this should be fixed, if it's not please leave a note here

**Closed by kyazdani42** 2021-06-02 17:25 UTC
