### ISSUE TITLE
multiple errors when opening nvim

### ISSUE THREAD

**Issue by SrWither** [kyazdani42/nvim-tree.lua#944] opened 2022-02-07 23:53 UTC
**OS**
FreeBSD 13.0 RELEASE p6

**Neovim version**
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5

**Nvim-tree version**
nvim-tree last commit

**Describe the bug**
When opening neovim various errors can occur.

in a normal directory:
![image](https://user-images.githubusercontent.com/59105868/152891419-a64ad459-8e87-4b41-85c6-d8bf7c9e69a4.png)

in a project with `git` when opening neovim ignores the dashboard:
![image](https://user-images.githubusercontent.com/59105868/152891548-22ef6113-a943-48b5-a729-6badff071634.png)

**To Reproduce**
open neovim

**Expected behavior**
![image](https://user-images.githubusercontent.com/59105868/152891692-a50d80c9-ec81-4f3b-a168-16c4da38403a.png)

**Comment by kyazdani42** [comment] 2022-02-08 07:58
duplicate of #942 , leaving that open because it's still relevant.

**Closed** 2022-02-08 20:43 UTC
