### ISSUE TITLE
When a plugin is lazily loaded, it closes immediately after the first launch.

### ISSUE THREAD

**Issue by nabezokodaikon** [kyazdani42/nvim-tree.lua#961] opened 2022-02-10 13:39 UTC
**OS**
Mac

**Neovim version**
```
NVIM v0.7.0-dev+1039-g19b2ad051
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nabezokodaikon@MacBook-Air.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-19b2ad0/share/nvim"

Run :checkhealth for more info
```

**Nvim-tree version**
master branch
da59247db9013dd48d2aa8086982f90ac9ef05c2 commit

**Describe the bug**
When a plugin is lazily loaded, it closes immediately after the first launch.

**To Reproduce**
Minimum init.vim
```vim
if &compatible
    set nocompatible
endif

let $CACHE = expand('~/.cache')

if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif

let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif

call dein#begin(s:dein_dir, expand('<sfile>'))

call dein#add('kyazdani42/nvim-web-devicons')
call dein#add('kyazdani42/nvim-tree.lua', {'lazy': 1, 'on_cmd': 'NvimTreeToggle', 'hook_source': 'lua require"nvim-tree".setup {}'})

call dein#end()

filetype plugin indent on
syntax enable
```

1. Start Neovim.
2. Run `call dein#update()` commnad.
3. Restart Neovim.
4. Run `NvimTreeToggle` command. 

**Expected behavior**
Lazy loading of plug-ins should not be closed immediately on the first launch.

**Comment by kyazdani42** [comment] 2022-02-10 17:50
duplicate of #958 , closing :)

**Closed by kyazdani42** 2022-02-10 17:50 UTC

**Comment by nabezokodaikon** [comment] 2022-02-11 01:11
Sorry. I didn't check.
I've confirmed that it's been fixed.
