### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by lucax88x** [kyazdani42/nvim-tree.lua#214] opened 2021-02-23 13:49 UTC
Is there a way to have tree opened as full screen, without a "right" window? 

I tried nvim_tree_width=100 but it's always 50% of the screen.

**Comment by kyazdani42** [comment] 2021-02-23 16:20
i think this is a kind of duplicate of #200. I don't know why it would take only 50%, but i believe the tree width is not expressed as % but as columns. this is why it doesn't open fullscreen, a PR to fix that would be gladly welcome.

**Comment by lucax88x** [comment] 2021-02-23 17:27
Dunno, I saw this one, but despite the title and confusing "description" I cannot relate to my problem.

What I want is that we don't open the "tree" as a side window, but as a full window, like opening a new file.

Exactly like the old netrw or dirvish are doing.

**Comment by kyazdani42** [comment] 2021-02-23 19:28
for me its kind of the same thing. I remember this request was made quite some time ago, but im not that interested in doing that but ill accept a PR that whishes to emulate this behavior. I also need to make a full rewrite of buffer/window handling I think itll make things easier.

**Comment by kyazdani42** [comment] 2021-08-28 09:43
closed in 3bac5633e1f7e7 `1.1.0`

**Closed by kyazdani42** 2021-08-28 09:43 UTC
Labels: enhancement

**Comment by lucax88x** [comment] 2021-08-31 08:46
@kyazdani42 so full screen is now working?

**Comment by kyazdani42** [comment] 2021-08-31 18:18
when you open it by default yes it should be fullscreen

**Comment by enheit** [comment] 2024-05-13 07:17
@kyazdani42 Is it possible to open nvim-tree in full screen when using `:NvimTreeOpen`?

I would expect to have something like this in the nvim-tree configuration.

```lua
config = {
  view = {
    fullscreen = true
  }
}
```

And it would look like this.

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/8645216/b4b66bfa-2437-4e3d-8561-743cede55bff)

But currently I can set only the width to "100%"

```lua
config = {
  view = {
    width = "100%"
  }
}
```

So, it 'kinda' solves the problem, but it's not opening the nvim-tree in a separate window; rather, it tries to expand it to full size (note the vertical line which divides between the current nvim-tree and the opened file).

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/8645216/63eeb4a2-6026-4972-888f-4f843885e6ad)

So, if I drag the terminal window, it behaves like this.

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/8645216/074747be-9971-4dfc-93ec-263dff848804)

I don't like such behavior and would like it to behave exactly the same as when we open the project for the first time, with only nvim-tree opened (as shown in the first screen). It indeed behaves like a full screen.

So, the question is: is it possible to achieve the 'real' full-size window experience with the current version of nvim-tree? If not, are there plans to add this to the library in the near future?

**Comment by alex-courtis** [comment] 2024-05-14 00:23
See `:help nvim-tree-api.tree.open()` `{current_window}` option.

Example mapping:
`vim.keymap.set("n", "<F11>", function() api.tree.open({ current_window = true }) end, { noremap = true })`

See [vinegar style](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes#vinegar-style) for some similar recipes.

**Comment by enheit** [comment] 2024-05-14 01:54
@alex-courtis Thanks, your suggestion works exactly as I wanted it to!
