### ISSUE TITLE
Buffer local options not working

### ISSUE THREAD

**Issue by Akin909** [kyazdani42/nvim-tree.lua#24] opened 2020-05-29 18:09 UTC
Congrats on merging the refactor :raised_hands:
Just tried it out and it feels even snappier :1st_place_medal:.

A strange issue I'm having that started before the refactor but has gotten worse, is that some buffer local options aren't working for some reason. The `nonumber` and `nolist` setting seems to now no longer be working.

![nvim-tree-options-bug](https://user-images.githubusercontent.com/22454918/83290817-33f9a880-a1df-11ea-93a8-5772a1d1ecfd.png)

I've tried with a minimal vimrc with just
```
call plug#begin(stdpath('data') . '/plugged')
Plug 'kyazdani42/nvim-tree.lua'
call plug#end()

set number relativenumber
set list
```
As you can see in the screenshot for some reason the `set local` call in `Tree.lua` isn't working I'm not really sure I understand. I also tried creating a `after/ftplugin/LuaTree.vim` to override things but that still didn't work.

If I remove the settings from my `init.vim` everything works but I need/like those settings not sure why the buffer isn't overriding it :confused:

**Comment by kyazdani42** [comment] 2020-05-29 18:45
thanks :)
well this is an issue i'm having a LOT when trying to set local options with lua... i don't know why it's causing this, i'm going to try reproduce it an fix it if i can.

**Comment by kyazdani42** [comment] 2020-05-29 18:53
well just found that setlocal doesn't work at all, but api.nvim_win_set_option does work. I guess it happens because these are window options and not buffer options, thus setlocal applying on the buffer does not work.

**Comment by kyazdani42** [comment] 2020-05-29 18:59
fixed in master

**Closed by kyazdani42** 2020-05-29 18:59 UTC
