### ISSUE TITLE
Invalid window id: 1000 after switching between a file and nvim-tree

### ISSUE THREAD

**Issue by JLighter** [kyazdani42/nvim-tree.lua#887] opened 2022-01-07 22:40 UTC
Hello !
I'm experiencing an error after switch from a file to the nvim-tree.

To reproduce :
- I open neovim on my current directory (nvim .)
- open a file
- hit CTRL-o (or CTRL-^) to go back to the explorer
- try to open a file (the same file or another)
- I now see this error and cannot open any file anymore :
`E5108: Error executing lua ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:100: Invalid window id: 1000
stack traceback:
        [C]: in function 'nvim_win_get_cursor'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:100: in function 'get_node_at_cursor'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:160: in function 'on_keypress'
        [string ":lua"]:1: in main chunk`

Am I doing something wrong ?
Thanks in advance

**Comment by arowe92** [comment] 2022-01-07 23:55
I get this too, just updated

**Comment by kyazdani42** [comment] 2022-02-05 11:31
Hi, sorry for the late answer.
I was not able to reproduce, could you share a minimal configuration file please ?

**Comment by kyazdani42** [comment] 2022-02-21 23:07
Hi again, i've made a lot of changes these last weeks, does this issue still appear ?

**Comment by JLighter** [comment] 2022-02-22 07:15
Hi ! I cannot go back to the tree buffer when hitting C-o or C-^ anymore so the bug is no longer relevant.

**Comment by kyazdani42** [comment] 2022-02-22 07:54
hi :) i'll close this then, let me know if this happen again

**Closed by kyazdani42** 2022-02-22 07:54 UTC
Labels: bug
