### ISSUE TITLE
Un-needed indentline over root dir 

### ISSUE THREAD

**Issue by siduck** [kyazdani42/nvim-tree.lua#802] opened 2021-11-28 07:04 UTC
Hi , I found this strange behaviour in which the root dir gets an indentline 

![image](https://user-images.githubusercontent.com/59060246/143732980-cff84925-dc43-4625-a631-1b2f72e2923c.png)

If I click on a dir then the indentline vanishes 

![image](https://user-images.githubusercontent.com/59060246/143733007-8c2b3ad9-dcbe-4591-8922-a8f058b24ed2.png)

I didnt face this issue before at all , I think some of changes in commits on Nov 27 caused it :(

**Comment by siduck** [comment] 2021-11-28 07:06
https://user-images.githubusercontent.com/59060246/143733101-0840a656-1e80-45b0-8067-22b6674a0d5a.mp4

**Comment by kyazdani42** [comment] 2021-11-28 13:24
cannot reproduce, would you mind sharing a minimal config ?

**Comment by siduck** [comment] 2021-11-28 13:50
> cannot reproduce, would you mind sharing a minimal config ?

hm I tried a minimal config and  didnt face any issue. Trying to figure out what might go wrong with my config 

my nvimtree config https://github.com/NvChad/NvChad/blob/dev/lua/plugins/configs/nvimtree.lua

**Comment by siduck** [comment] 2021-11-28 13:51
I faced this issue after updating the plugin yesterday : 

https://user-images.githubusercontent.com/59060246/143770701-36574d1c-6849-40bb-8b37-a0f6df2f79e6.mp4

**Comment by kyazdani42** [comment] 2021-11-28 14:23
i managed to reproduce, when using `arrows = 1` and indent markers at the same time. I'll fix this.

**Comment by kyazdani42** [comment] 2021-11-28 14:25
shoud be fixed in latest master

**Closed by kyazdani42** 2021-11-28 14:25 UTC
