### ISSUE TITLE
Hooking onto internal api

### ISSUE THREAD

**Issue by SystematicError** [kyazdani42/nvim-tree.lua#917] opened 2022-01-27 14:44 UTC
Hey, I've been using this plugin for my neovim workflow and its been working beautifully, recently however, I switched from `bufferline.lua` to `barbar.nvim`, the transition was smooth, however one feature I miss was the ability for the bar to be automatically offset when a buffer (such as the file tree) is present. BarBar does somewhat support this, however the bar offset has to be set manuall.

I was wondering if it is somehow possible for nvim-tree to call a function which I define whenever the tree is opened, closed, or resized. I would also like for the function to somehow access the tree's current width.

**Comment by kyazdani42** [comment] 2022-02-01 08:35
I don't think you can do a function on resize, but you could maybe hook into `au BufEnter NvimTree ...` and get the width via `vim.api.nvim_win_get_width(tree_window)`

**Comment by alex-courtis** [comment] 2022-04-03 05:55
Duplicate of #575

**Closed by alex-courtis** 2022-04-03 05:55 UTC
Labels: question, feature request
