### ISSUE TITLE
the explorer does not focus on current file on the first open time.

### ISSUE THREAD

**Issue by thuan1412** [kyazdani42/nvim-tree.lua#777] opened 2021-11-08 17:39 UTC
https://user-images.githubusercontent.com/36019052/140791133-b3c3b3ae-2c65-4be9-abea-aa7a62cfe964.mp4

**Comment by kyazdani42** [comment] 2021-11-27 13:01
cannot reproduce. Please give me more informations.

**Comment by thuan1412** [comment] 2021-11-27 13:44
My nvim's version is 0.6 and here is my nvim-tree configuration. https://github.com/thuan1412/NvChad/blob/main/lua/plugins/configs/nvimtree.lua.

**Comment by ShivamKumar2002** [comment] 2022-01-11 07:47
+1
I am also facing same issue

**Comment by kyazdani42** [comment] 2022-02-05 11:27
Is this still relevant ? The `update_focused_file.enable` should be true in the setup

**Comment by kyazdani42** [comment] 2022-02-21 22:59
i believe this is fixed now, closing.

**Closed by kyazdani42** 2022-02-21 22:59 UTC
