### ISSUE TITLE
Stack trace when toggling with multiple tabs

### ISSUE THREAD

**Issue by igorlfs** [kyazdani42/nvim-tree.lua#1184] opened 2022-04-23 13:49 UTC
### Description

When opening nvim-tree in more than one tab, closing nvim-tree's split moves you to the next tab with nvim-tree open (as opposed to leaving you in the same tab as you were before) and subsequently closing nvim-tree in this tab throws a stack trace.

### Neovim version

```markdown
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.17.3-artix1-1 

### nvim-tree version

ebf73f0

### Steps to reproduce

1. `nvim -nu /tmp/nvt-min.lua`
2.  `:NvimTreeOpen`
3.  `:tabnew`
4.  `:NvimTreeOpen`
5.  return to the first tab, eg `gt` (this is only necessary to reproduce the "closing nvim-tree's window moves you to the next tab with nvim-tree open", as the stack trace is thrown regardless)
6. `:NvimTreeClose` - at this stage you should have been moved to the second tab
7. `:NvimTreeToggle` results in
```
E5108: Error executing lua ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:81: Vim:E95: Buffer with this name already exists                                                                    
stack traceback:
        [C]: in function 'nvim_buf_set_name'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:81: in function 'create_buffer'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:190: in function 'open'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:97: in function 'open_view_and_draw'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:123: in function 'open'
        ...n/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:47: in function 'open'
        ...n/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:31: in function 'toggle'
        [string ":lua"]:1: in main chunk
```
Also, if in step 7 you try to run `:NvimTreeClose` instead, nvim-tree's split won't be closed and no error message will be thrown.

### Expected behavior

Nvim-tree should close normally when used with multiple tabs.

### Actual behavior

Either an error is thrown or nvim-tree isn't closed at all.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

_G.setup = function()
  require("nvim-tree").setup {}
end
```

**Comment by alex-courtis** [comment] 2022-04-24 02:34
Successfully replicated.

**Comment by alex-courtis** [comment] 2022-04-24 03:33
[#1184-all-tabpages-closed](https://github.com/kyazdani42/nvim-tree.lua/tree/%231184-all-tabpages-closed)

@igorlfs I would be grateful it you could test this branch `#1184-all-tabpages-closed`

**Comment by RobertAudi** [comment] 2022-04-24 10:58
@alex-courtis I tried with `#1184-all-tabpages-closed` and with `master` (since I saw that the branch was merged) and I still get the error 😕

**Comment by igorlfs** [comment] 2022-04-24 14:35
> @alex-courtis I tried with #1184-all-tabpages-closed and with master (since I saw that the branch was merged) and I still get the error

Oddly enough, I tried with master and the stack trace is now gone. However, I'm still observing the tab change when closing nvim-tree's split. I was unable to find a pattern for this behavior, though. My current guess is that you're moved to the last tab where nvim-tree was open, but only under certain conditions I wasn't able to pinpoint.

**Comment by alex-courtis** [comment] 2022-04-25 01:37
> As a matter of fact, now every time I open the tree using toggle (except the first time) I get the same error, even with a single tab.

That is a problem. Unfortunately I cannot replicate that.

Please use a minimal configuration as per a [bug report](https://github.com/kyazdani42/nvim-tree.lua/issues/new/choose) and describe the exact steps necessary to reproduce the issue.

**Comment by alex-courtis** [comment] 2022-04-25 02:01
> However, I'm still observing the tab change when closing nvim-tree's split. I was unable to find a pattern for this behavior, though.

toggle first
open file
new tab
toggle second
open file
toggle second
toggle second
toggle first
toggle first
toggle second

**Comment by RobertAudi** [comment] 2022-04-26 04:04
@alex-courtis @igorlfs I just realized that the problem comes from [stickybuf.nvim](https://github.com/stevearc/stickybuf.nvim) and not nvim-tree. By removing the plugin the problem went away. So as far as I'm concerned this is a non problem

**Comment by kyazdani42** [comment] 2022-04-26 19:26
tabpage management can conflict i believe. Nvim-tree shouldn't fail because of another plugin :)

**Comment by kyazdani42** [comment] 2022-04-30 14:32
@RobertAudi haven't been able to reproduce with stickybuf.nvim. Actually, i implement the behavior of stickybuf inside nvim-tree to avoid the tree buffer to be overridden :) 
I'll close this soon if no-one can give us a complete minimal configuration to reproduce this issue.

**Comment by alex-courtis** [comment] 2022-05-01 02:46
The stack is definitely fixed, althought I did find a [minimal config reproducer](https://github.com/kyazdani42/nvim-tree.lua/issues/1184#issuecomment-1107986323) of the "unwanted tab switch" behaviour.

I'm not sure whether that case is worth fixing.

**Comment by igorlfs** [comment] 2022-05-01 13:01
Should I close this issue and open a separate one for the unwanted tab switch?

**Comment by alex-courtis** [comment] 2022-05-01 23:44
> Should I close this issue and open a separate one for the unwanted tab switch?

That would be great; thank you @igorlfs

**Closed** 2022-05-02 13:01 UTC
Labels: bug, awaiting feedback
