### ISSUE TITLE
quit as last buffer 

### ISSUE THREAD

**Issue by YanzhaoW** [kyazdani42/nvim-tree.lua#1368] opened 2022-06-21 13:35 UTC
### Description

Without any configuration, neovim simply doesn't quit as nvim-tree is the last buffer. Many people suggest, as is also mentioned in the README.md (#1115 ), that I should add following command:
```
vim.api.nvim_create_autocmd("BufEnter", {
  nested = true,
  callback = function()
    if #vim.api.nvim_list_wins() == 1 and vim.api.nvim_buf_get_name(0):match("NvimTree_") ~= nil then
      vim.cmd "quit"
    end
  end
})
```
This is very bad solution because it can cause neovim to crash if you accidentally quit without saving. Following errors will be repeated if you press any key in neovim:
```
Press ENTER or type command to continue
Error executing vim.schedule lua callback: ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:378: Vim(append):Error executing lua callback: /home/ywang/.config/nvim/lua/plugs/n
vimtree_config.lua:34: Vim(quit):E37: No write since last change
stack traceback:
        [C]: in function 'cmd'
        /home/ywang/.config/nvim/lua/plugs/nvimtree_config.lua:34: in function </home/ywang/.config/nvim/lua/plugs/nvimtree_config.lua:32>
        [C]: in function 'nvim_win_close'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:378: in function <...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:356>
stack traceback:
        [C]: in function 'nvim_win_close'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:378: in function <...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:356>
Press ENTER or type command to continue
```
I would suggest remove this tip in the README.md.

Is there any other doable solution to quit neovim when the nvim-tree is the last buffer?

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Minimal config

```lua
require'nvim-tree'.setup{
    view = {
        side = 'right'
    },
    update_focused_file = {
        enable = true,
        update_cwd = true,
        ignore_list = {}
    }
}
-- vim.cmd([[autocmd BufEnter * ++nested if winnr('$') == 1 && bufname() == 'NvimTree_' . tabpagenr() | quit | endif]])
vim.api.nvim_create_autocmd("BufEnter", {
  nested = true,
  callback = function()
    if #vim.api.nvim_list_wins() == 1 and vim.api.nvim_buf_get_name(0):match("NvimTree_") ~= nil then
      vim.cmd "quit"
    end
  end
})
```

### Steps to reproduce

1. open a file using nvim with nvim-tree
2. edit a file
3. quit without saving
4. error occurs and is repeated when you press any key

**Comment by alex-courtis** [comment] 2022-06-25 02:38
This is a difficult vim problem with no good solution. It's not specific to nvim-tree.
- `BufEnter` is the last event that can be acted upon and that event can have side effects
- vim events are unpredictably ordered, especially when other plugins and automation is involved

Any and all ideas are welcome!

There is a warning in the readme, adding this issue to the warning.

**Comment by kyazdani42** [comment] 2022-06-25 08:48
This is unsupported feature so we won't try to hack to much around this.

**Comment by alex-courtis** [comment] 2022-06-26 01:38
See https://github.com/kyazdani42/nvim-tree.lua/issues/1005#issuecomment-1166393398

**Comment by Hxyspace** [comment] 2022-06-26 09:07
You can add the following command to close nvim-tree before exiting neovim, this will print the error message only once on error.
`vim.api.nvim_create_autocmd("BufEnter", {
    nested = true,
    callback = function()
        if #vim.api.nvim_list_wins() == 1 and vim.api.nvim_buf_get_name(0):match("NvimTree_") ~= nil then
            vim.cmd "NvimTreeClose"
            vim.cmd "quit"
        end
  end
})
`

**Comment by kyazdani42** [comment] 2022-06-26 10:13
closing this, since we don't plan to help more with this undesirable feature :)

**Closed by kyazdani42** 2022-06-26 10:13 UTC
Labels: documentation, PR please

**Comment by beauwilliams** [comment] 2022-07-26 13:17
I might have the final piece for a decent working implementation, using `set confirm` we get a nice exit and prevents kicking you back into vim. It will prompt you to `[Y]es, (N)o, Save (A)ll, (D)iscard All, (C)ancel`

I've also opted to parse the window layout instead of getting number of windows as this sometimes can be incorrect. I think the most reliable way to deal with these matters is parsing the window layout which is easy for this little problem :) 

This solution even works for tabs (closest tab if nvimtree is last, leaving remaining tabs open)

Full snippet 
```lua
  vim.o.confirm = true
  vim.api.nvim_create_autocmd("BufEnter", {
	group = vim.api.nvim_create_augroup("NvimTreeClose", {clear = true}),
	callback = function()
		local layout = vim.api.nvim_call_function("winlayout", {})
		if layout[1] == "leaf" and vim.api.nvim_buf_get_option(vim.api.nvim_win_get_buf(layout[2]), "filetype") == "NvimTree" and layout[3] == nil then vim.cmd("quit") end
	end
})
```

I also made a branch here was considering doing a PR but depends on what other people think. 
https://github.com/beauwilliams/nvim-tree.lua/tree/auto-exit-last-window

**Comment by austinwilcox** [comment] 2022-07-26 13:38
@beauwilliams That works fantastic! Just implemented it and played around with it for a little bit. I didn't run into any errors or issues.

**Comment by beauwilliams** [comment] 2022-07-26 13:45
Awesome! Glad its doing the trick also for you mate @austinwilcox. The confirm seems to works well for unsaved buffers you can even hit esc and it closes the prompt and opens the unsaved buffer as you would expect

**Comment by austinwilcox** [comment] 2022-07-26 13:48
@beauwilliams I did just run into one potential problem. When I run nvim . the only tab open is nvim-tree, when I try to FZF, I get an error about opening plenary, and then when I click a file or anything, it just closes nvim.
Error executing Lua callback: ...ack/packer/start/plenary.nvim/lua/plenary/popup/init.lua:408: Failed to switch to window 1006
stack traceback:
        [C]: in function 'nvim_set_current_win'
        ...ack/packer/start/plenary.nvim/lua/plenary/popup/init.lua:408: in function 'create'
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:327: in function '_create_window'
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:397: in function 'find'
        ...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:126: in function 'v'
        ...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:529: in function 'v'
        ...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:514: in function <...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:483>
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:188: in function 'run_command'
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
        ...te/pack/packer/start/telescope.nvim/plugin/telescope.lua:109: in function <...te/pack/packer/start/telescope.nvim/plugin/telescope.lua:108>

Now this isn't to big of a deal for me, I don't often fuzzy find my way into a file when I first open a project, but just something to note.

**Comment by beauwilliams** [comment] 2022-07-26 13:57
Thanks for pointing that out could reproduce on my end too. That's a tough edge case, ah feels back to drawing board haha. I mean this is an improvement but still not perfect

**Comment by beauwilliams** [comment] 2022-07-26 14:28
@austinwilcox Okay, I have solved that bug now too on my end give this a shot

```lua
  vim.api.nvim_create_autocmd("BufEnter", {
	group = vim.api.nvim_create_augroup("NvimTreeClose", {clear = true}),
  pattern = "NvimTree_*",
	callback = function()
		local layout = vim.api.nvim_call_function("winlayout", {})
		if layout[1] == "leaf" and vim.api.nvim_buf_get_option(vim.api.nvim_win_get_buf(layout[2]), "filetype") == "NvimTree" and layout[3] == nil then vim.cmd("confirm quit") end
	end
})
```

**Comment by austinwilcox** [comment] 2022-07-26 14:36
@beauwilliams Unfortunately it still doesn't work for me. It will at least pull up Telescope and let me look for files, but when I try to open up one of the files, it closes nvim.

**Comment by beauwilliams** [comment] 2022-07-26 14:38
> @beauwilliams Unfortunately it still doesn't work for me. It will at least pull up Telescope and let me look for files, but when I try to open up one of the files, it closes nvim.

Oh yes right I forgot it was not meant to close. Yes the error is gone but now it exits. Hmm..

**Comment by julianpoy** [comment] 2022-11-10 22:05
@beauwilliams any solution to that last issue? So close to perfect!

**Comment by alex-courtis** [comment] 2022-11-13 04:49
@beauwilliams @austinwilcox @julianpoy I have added a [wiki page](https://github.com/nvim-tree/nvim-tree.lua/wiki/Auto-Close) covering auto close.

I have added the above solution as it does function in a minimal setup. Please update if you have any new discoveries or enhancements!

**Comment by ppwwyyxx** [comment] 2023-04-17 23:54
Solutions based on `BufEnter` has a problem that if I use `nvim some_directory/`, nvim will starts and immediately exits.
Solutions based on `QuitPre` are better. I use this:
```lua
vim.api.nvim_create_autocmd("QuitPre", {
  callback = function()
    local invalid_win = {}
    local wins = vim.api.nvim_list_wins()
    for _, w in ipairs(wins) do
      local bufname = vim.api.nvim_buf_get_name(vim.api.nvim_win_get_buf(w))
      if bufname:match("NvimTree_") ~= nil then
        table.insert(invalid_win, w)
      end
    end
    if #invalid_win == #wins - 1 then
      -- Should quit, so we close all invalid windows.
      for _, w in ipairs(invalid_win) do vim.api.nvim_win_close(w, true) end
    end
  end
})
```

**Comment by alex-courtis** [comment] 2023-04-18 01:32
> Solutions based on `BufEnter` has a problem that if I use `nvim some_directory/`, nvim will start and immediately exit.
> Solutions based on `QuitPre` are better. I use this:

That's nice. I'd be most grateful if you added it to [wiki: Auto Close](https://github.com/nvim-tree/nvim-tree.lua/wiki/Auto-Close)

**Comment by lliuaotian** [comment] 2024-05-10 10:27
> @austinwilcox Okay, I have solved that bug now too on my end give this a shot. If so fingers crossed this is the one 好吧，我现在也解决了这个错误，请尝试一下。如果是这样的话，那就是这个了↳
> 
> ```lua
> vim.api.nvim_create_autocmd("BufEnter", {
>   group = vim.api.nvim_create_augroup("NvimTreeClose", {clear = true}),
>   pattern = "NvimTree_*",
>   callback = function()
>     local layout = vim.api.nvim_call_function("winlayout", {})
>     if layout[1] == "leaf" and vim.api.nvim_buf_get_option(vim.api.nvim_win_get_buf(layout[2]), "filetype") == "NvimTree" and layout[3] == nil then vim.cmd("confirm quit") end
>   end
> })
> ```

Thanx,it helped me solve the problem.
