### ISSUE TITLE
Nvim crashes when file explorer is opened for code bases with many files and folders

### ISSUE THREAD

**Issue by tabot-kevin** [kyazdani42/nvim-tree.lua#666] opened 2021-09-29 14:47 UTC
when open the file explorer for code bases with many files and folders, the moment I start moving with the arrow, all the folders in the folder tree starts automatically expanding then it seems like there is some sort of file indexing happened, my computer's fan speed increases, then after a while nvim will freeze even quitting it becomes impossible till I click the X to terminate it, then error shown below will show.

<img width="1435" alt="1" src="https://user-images.githubusercontent.com/81575086/135292432-e2f6aa76-3b9b-4653-9898-88cf039f57db.png">

<img width="1920" alt="Screen Shot 2021-09-29 at 3 39 05 PM" src="https://user-images.githubusercontent.com/81575086/135292535-38a3edda-0d47-4dfe-9266-05d8c840d8b1.png">

**Comment by kyazdani42** [comment] 2021-10-02 21:17
i'd need more context, i've tested this plugin on huge folders and never had an issue. Did you check #549 ?

**Comment by kyazdani42** [comment] 2022-02-21 22:48
closing since no news. Tell me if you can point me towards something more reliable to reproduce (tested on a 20K folder of symlinks and such, there is not such things as a crash).

**Closed by kyazdani42** 2022-02-21 22:48 UTC
