### ISSUE TITLE
New files do not appear in tree until nvim restart

### ISSUE THREAD

**Issue by kristijanhusak** [kyazdani42/nvim-tree.lua#390] opened 2021-05-20 10:26 UTC
Hi,

today I noticed that new files added do not appear in the tree. I tried refreshing with `R`, but no luck. They appear only after I restart neovim. Is there a way to refresh the tree somehow?

Edit: Same thing for editing file name.

**Comment by AnthonyK213** [comment] 2021-05-20 13:33
It seems that this is a issue of `NVIM v0.5.0-dev+1339-g5d9c56012`.

**Comment by marcelarie** [comment] 2021-05-20 13:55
This happens to me too with  `NVIM v0.5.0-dev+1339-g5d9c56012`

**Comment by kyazdani42** [comment] 2021-05-20 19:28
https://github.com/neovim/neovim/pull/12076 might be related ? I cannot reproduce with the latest `NVIM v0.5.0-dev+1340-g3bd9cce36`.

**Comment by cervinka** [comment] 2021-05-20 20:17
Last commit of neovim, that works with nvim-tree is 6deae3d14b59f554a352b9e3738a7a4acb254ea3
commit 7fbf3bf18ba76832af7668fd85e4bd817bb378f1 has the mentioned issues.

Even the last neovim commit (3bd9cce3686f9bf0ed127be07d9812d8cb19bfd2) doesn't work for me.

**Comment by marcelarie** [comment] 2021-05-20 20:22
> [neovim/neovim#12076](https://github.com/neovim/neovim/pull/12076) might be related ? I cannot reproduce with the latest `NVIM v0.5.0-dev+1340-g3bd9cce36`.

To reproduce I only need to create a file/folder from nvim-tree with `a`. 
The file only appears when I reopen nvim. `NVIM v0.5.0-dev+1340-g3bd9cce36`  haves the same problem.

**Comment by kyazdani42** [comment] 2021-05-20 20:34
oh you are right :/ that's troubling... i'll push a fix if i can find the culprit :(

**Comment by kyazdani42** [comment] 2021-05-20 20:37
fixed in ef570074e0f73e

**Closed by kyazdani42** 2021-05-20 20:37 UTC

**Comment by marcelarie** [comment] 2021-05-20 20:51
I can confirm that now the files appear when creating them. But for some reason delete doesn't work. You can see it at the end of the record.
[![asciicast](https://asciinema.org/a/O6Ih8bKXHtwQbJulAsKRT6VMY.svg)](https://asciinema.org/a/O6Ih8bKXHtwQbJulAsKRT6VMY)

**Comment by kyazdani42** [comment] 2021-05-21 06:38
cannot reproduce, do you have an up to date version of neovim ?

**Comment by marcelarie** [comment] 2021-05-21 15:45
right now `NVIM v0.5.0-dev+1340-g3bd9cce36`
