### ISSUE TITLE
Error on running plugin: "Error executing lua ...view.lua:61: Expected lua string"

### ISSUE THREAD

**Issue by callumacrae** [kyazdani42/nvim-tree.lua#1031] opened 2022-02-28 15:40 UTC
**OS**
Operation system's name and version
Mac OS 11.6

**Neovim version**
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur
```

**Nvim-tree version**
`48e76bc` - latest master

Here's my config: https://github.com/callumacrae/dotfiles/blob/master/vim/config/plugin-config/nvim-tree.lua

**Describe the bug**
When I run `:NvimTreeOpen`, I sometimes get the following error:

```
E5108: Error executing lua .../share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:61: Expected lua string
stack traceback:
        [C]: in function '__index'
        .../share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:61: in function 'create_buffer'
        .../share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:156: in function 'open'
        ...l/share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/lib.lua:110: in function 'open_view_and_draw'
        ...l/share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/lib.lua:141: in function 'open'
        ...local/share/nvim/plugged/nvim-tree.lua/lua/nvim-tree.lua:43: in function 'open'
        [string ":lua"]:1: in main chunk
```

The tree doesn't open, and it renames the current buffer to "NvimTree" (and if I run the command again, it closes it)

I get the error for the entire session and every time i open vim until i change some config and back again - I don't understand this and it makes it very difficult to debug what could be causing the issue.

**To Reproduce**
Happens every time I run `:NvimTreeOpen` or any other nvim-tree commands, on some vim sessions

**Expected behavior**
should open nvim-tree

Presumably this is specific to my system or config as I haven't seen any other issues, but not sure where to look or what to change!

**Comment by kyazdani42** [comment] 2022-02-28 21:01
I cannot reproduce your issue, but the tree is heavily not working given your config. I'll try to pinpoint the issue.

**Comment by callumacrae** [comment] 2022-03-01 09:50
is there any other info i can provide that would help? i'm comfortable poking around in lua files but didn't really know where to start in this case

**Comment by zoshima** [comment] 2022-03-01 12:49
I started to have the same issue after upgrading my packages earlier today. Also MacOS and NVIM v0.6.1
```
E5108: Error executing lua ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:61: Expected lua string
stack traceback:
        [C]: in function '__index'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:61: in function 'create_buffer'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:156: in function 'open'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:112: in function 'open_view_and_draw'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:143: in function 'open'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:43: in function 'open'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:28: in function 'toggle'
        [string ":lua"]:1: in main chunk
```

**Comment by callumacrae** [comment] 2022-03-01 13:05
@zoshima which packages did you update? if it was this plugin, which version were you on before?

also, does it happen every time?

**Comment by kyazdani42** [comment] 2022-03-01 19:18
it's happening when setting buffer option through `vim.bo`. Could you try these in vim:
```
:lua vim.bo[0].swapfile = false
:lua vim.bo[0].buftype = 'nofile'
:lua vim.bo[0].modifiable = false
:lua vim.bo[0].filetype = 'NvimTree'
:lua vim.bo[0].bufhidden = 'wipe'
:lua vim.bo[0].buflisted = false
:lua vim.bo[0].swapfile = false
```
If an error occur on one of the option, can you tell me ?

**Comment by kyazdani42** [comment] 2022-03-02 20:30
Looks like the buffer number passed in is wrong somehow. This might be related to nvim-tree trying to hijack a buffer it should not. I'm not sure since i've never seen this happening.

**Comment by callumacrae** [comment] 2022-03-03 11:27
cool i'll just try to get as much info as i can next time it happens (although it hasn't happened in a couple days) and post it here :)

**Comment by kyazdani42** [comment] 2022-03-03 20:11
if you cannot reproduce this in a week or two i'll close it then :)

**Comment by RobWalt** [comment] 2022-03-04 08:24
This also happens for me. I'm on Manjaro Linux. It seems to happen when I open a lot of buffers.
I get this quite frequently.

I use nvim-lsp, it happens for me in this exact case:

1. I jump to the definition of some symbol (It opens a new buffer for the destination where to jump to)
2. I jump back to the buffer that contains the use of the symbol with `<C+o>`
3. I try to open `nvim-tree` with my keybinding, which invokes `NvimTreeFindFileToggle` (the same happens for `NvimTreeOpen`)

Note that this only happens after jumping back. A can still open `nvim-tree` after jumping into the buffer that contains the definition.

**Comment by RobWalt** [comment] 2022-03-04 08:32
After some more testing, I found out more about the cause. The issue seems to be related to the case where
`actions.open_file.quit_on_open = true`
(at least in my case)

I've turned it off for now as a quick fix.

**Comment by RobWalt** [comment] 2022-03-04 10:51
Nevermind. It still happens. However less frequently.

**Comment by RobWalt** [comment] 2022-03-04 11:05
Another thing to add here: (I don't know if that helps)
After the error shows up, a new file is created, which is called `NvimTree_1` and the changes made up to the point of trying to open nvim-tree are dumped there. The file is located in the directory where neovim was originally started.

**Comment by callumacrae** [comment] 2022-03-04 11:28
> It seems to happen when I open a lot of buffers.

i always have a lot of buffers open - have about 200 atm but i think i had 300-400 when the problem last occurred. maybe explains why it hasn't happened in a while as i closed them all

I use nvim-lsp and those steps to replicate aren't causing the issue for me atm

> After the error shows up, a new file is created, which is called NvimTree_1 and the changes made up to the point of trying to open nvim-tree are dumped there. The file is located in the directory where neovim was originally started.

The exact same happens for me so it sounds like this is definitely the same issue!

**Comment by tuyentv96** [comment] 2022-03-04 23:46
This same issue happens for me when I turn on the `quit_on_open` setting.

**Closed** 2022-03-06 11:01 UTC
Labels: bug

**Comment by RobWalt** [comment] 2022-03-07 07:38
Awesome, thanks! 🔥 🎉

**Comment by callumacrae** [comment] 2022-03-07 10:10
amazing, thank you!
