### ISSUE TITLE
Automatically resize horizontally

### ISSUE THREAD

**Issue by xbladesub** [kyazdani42/nvim-tree.lua#1309] opened 2022-05-30 05:08 UTC
I have a problem with automatically resizing. Is it possible to fix?
<img width="354" alt="Screen Shot 2022-05-30 at 1 05 20 PM" src="https://user-images.githubusercontent.com/45129790/170920727-88537052-d024-4f41-a129-e32429a46b79.png">

**Comment by alex-courtis** [comment] 2022-05-30 06:20
Work in progress: #1293

**Comment by kyazdani42** [comment] 2022-05-30 10:51
duplicate of #865, closing

**Closed by kyazdani42** 2022-05-30 10:51 UTC
Labels: question
