### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by CanKolay3499** [kyazdani42/nvim-tree.lua#769] opened 2021-11-06 10:59 UTC
Hi, I'm rewriting my neovim config with lua. Before using nvim tree I can create files/folders successfuly in the nerdtree but now I cant create files with nvimtree 
![Screenshot_20211106-135539_Termux](https://user-images.githubusercontent.com/80613396/140607194-fd833c29-e541-4091-88d0-7fa776c0d41a.jpg)

**Comment by kyazdani42** [comment] 2021-11-27 12:45
hum this might be quite hard for me to reproduce :smile: not sure where to look, and debugging on mobile would be a nightmare.

**Comment by CanKolay5677** [comment] 2021-11-27 13:01
Can you write some code that won't create `/data/data` folder in android? Because android wont allow to access `/data/data` folder without root.

![Screenshot_20211127-154731_Termux](https://user-images.githubusercontent.com/80613396/143681897-e2e24687-6d32-47a7-8273-6dd295dc6d1f.jpg)

**Comment by kyazdani42** [comment] 2021-11-27 13:20
as you are able to test this, i'd suggest you to write the code in this case :)

**Comment by CanKolay5677** [comment] 2021-11-27 13:39
I'm searching for that but I found this code in `fs.lua`

```lua
local success = luv.fs_mkdir(path_to_create, 493)```

What is 493 mean?

**Comment by HONESTFLY** [comment] 2021-12-24 16:07
can you help me

**Comment by Ae-Mc** [comment] 2022-01-20 20:45
Same problem

**Comment by Ae-Mc** [comment] 2022-01-21 01:38
@CanKolay3499 I created fork and fixed the issue. You can use it for now until pull request not merged.

**Closed** 2022-01-21 09:45 UTC
Labels: bug
