### ISSUE TITLE
how to use `actions.open_file.quit_on_open`

### ISSUE THREAD

**Issue by anurag3301** [kyazdani42/nvim-tree.lua#1094] opened 2022-03-21 13:36 UTC
Hey I used to use a option that closes nvim-tree as I open a file like mentioned below.
```lua
vim.cmd("let g:nvim_tree_quit_on_open = 1")
```
But it has been deprecated and the new usage is like this
`nvim_tree_quit_on_open` -> `actions.open_file.quit_on_open`
As mentioned in this [issue](https://github.com/kyazdani42/nvim-tree.lua/issues/674)
I tried adding this in following way but it isnt working
```diff
require'nvim-tree'.setup {
  disable_netrw       = true,
  hijack_netrw        = true,
  open_on_setup       = false,
  ignore_ft_on_setup  = {},
  auto_close          = true,
  open_on_tab         = false,
  update_to_buf_dir   = {
    enable = true,
    auto_open = true,
  },
  hijack_cursor       = false,
  update_cwd          = false,
  diagnostics = {
    enable = false,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    }
  },

+  actions = {
+    open_file = {
+       quit_on_open = true,
+	},
+  },

  update_focused_file = {
    enable      = false,
    update_cwd  = false,
    ignore_list = {}
  },
  system_open = {
    cmd  = nil,
    args = {}
  },

  view = {
    width = 30,
    height = 30,
    side = 'left',
    auto_resize = false,
    mappings = {
      custom_only = false,
      list = {}
    }
  }
}
```
How Should I use this option

**Comment by kyazdani42** [comment] 2022-03-21 14:16
did you reload you editor properly ? just tried this it works as expected.

**Comment by Samyak2** [comment] 2022-03-21 17:55
I have noticed this issue in my configuration too. My configuration (notice the `actions` part):
```lua
require'nvim-tree'.setup {
    auto_close = true,
    auto_reload_on_write = true,
    update_focused_file = {
        enable      = true
    },
    diagnostics = {
        enable = false,
    },
    actions = {
        open_file = {
            quit_on_open = true,
        }
    }
}
```

The nvim tree window does not quit when I open a file through it. I have also confirmed that this configuration file is being loaded correctly, so the setup function is being called.

**Comment by anurag3301** [comment] 2022-03-21 18:19
> 

Yeah, not try adding the following line at the bottom of your config file, it should work. Nvim-tree should auto close
```lua
vim.cmd("let g:nvim_tree_quit_on_open = 1")
```

**Comment by BitInByte** [comment] 2022-03-22 12:21
I'm having exactly the same issue, it is not working when added to the setup but works properly when I use the old way, just with the warning...

**Comment by kyazdani42** [comment] 2022-03-22 19:11
I can definitely not reproduce. Are you sure you are on latest master ?

**Comment by Samyak2** [comment] 2022-03-23 06:31
Yes, I'm on latest master.

Could it be because of conflicts with another plugin? Here is my config for reference - https://github.com/Samyak2/nvim-config/blob/main/lua/plugins.lua. @anurag3301 or @BitInByte could you post your config too?

**Comment by anurag3301** [comment] 2022-03-23 11:16
@Samyak2 Yeah That might also be a possible reason, Ill look into your config
this is mine [https://github.com/anurag3301/my-linux-setup/blob/main/config/nvim/lua/plugins.lua](https://github.com/anurag3301/my-linux-setup/blob/main/config/nvim/lua/plugins.lua)

**Comment by gegoune** [comment] 2022-03-23 11:28
Did you manage to replicate it with minimal config?

**Comment by BitInByte** [comment] 2022-03-23 11:53
Here is my config as well: https://github.com/BitInByte/.dotfiles

**Comment by gegoune** [comment] 2022-03-23 12:07
Try with minimal config from https://github.com/kyazdani42/nvim-tree.lua/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml, it will ensure nothing else is interfering.

**Comment by anurag3301** [comment] 2022-03-23 12:38
Well I added the following in `/tmp/nvt-min.lua` with the action in setup
```diff
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
+      actions = {
+        open_file = {
+            quit_on_open = true,
+        }
    }
  }
end
```
And ran `nvim -nu /tmp/nvt-min.lua`, The `quit_on_open` works.
Then what might be messing it up?😩

**Comment by alex-courtis** [comment] 2022-03-24 00:18
> ```lua
> vim.cmd("let g:nvim_tree_quit_on_open = 1")
> ```

That is a legacy option, which has moved to `actions.open_file.quit_on_open`. It is automatically moved on nvim-tree start, so the two have the same effect.

**Comment by alex-courtis** [comment] 2022-03-24 00:26
> And ran `nvim -nu /tmp/nvt-min.lua`, The `quit_on_open` works.
> Then what might be messing it up in our config and why the old way works?

You could add all your options (including the `g:`s) to `nvt-min.lua` then remove individual options until the tree behaves as you expect.

If it is working as intended with all your options, you could start adding your plugins and other nvim configuration until you see a failure.

**Comment by alex-courtis** [comment] 2022-03-24 00:38
> And ran `nvim -nu /tmp/nvt-min.lua`, The `quit_on_open` works. Then what might be messing it up in our config and why the old way works?weary

Are you absolutely certain you are running the latest version? The minimal configuration is. Compare:
`cd /tmp/nvt-min/site/pack/packer/start/nvim-tree.lua ; git log --format='%h' -n 1`
`cd <your plugins directory>t/nvim-tree.lua ; git log --format='%h' -n 1`

**Comment by BitInByte** [comment] 2022-03-28 10:17
I am running the latest version. I also cleaned up and tried with all of the options you have in the README. None of them works.

**Comment by kyazdani42** [comment] 2022-03-28 17:02
@BitInByte looking at your config you are calling setup only in your plugins.lua file that's why options does not work.

**Comment by BitInByte** [comment] 2022-03-28 20:12
It is showing me the warning alert to don’t use the old version anymore. Does it have anymore versions after that? I made PackerUpdate a couple of times already and this behaviour still persists

**Comment by kyazdani42** [comment] 2022-03-29 17:51
you need to remove the `g:nvim_tree_quit_on_open` option and set it in the setup function

**Comment by BitInByte** [comment] 2022-03-29 19:24
That’s what I’ve done already @kyazdani42 and it doesn’t work. Only works if I have that option, without it and with the set on the setup function it doesn’t work, at least in my machine with my config

**Comment by alex-courtis** [comment] 2022-03-29 23:55
> Only works if I have that option, without it and with the set on the setup function it doesn’t work, at least in my machine with my config

@BitInByte 

Please enable logging as per https://github.com/kyazdani42/nvim-tree.lua/issues/1094#issuecomment-1076941977 . We can see if it is a problem with the parsing of your setup options, specifically whether nvim-tree is using your value of `actions.open_file.quit_on_open` or the default.

Please also try a minimal configuration. anurag3301 was successful with the minimal configuration: https://github.com/kyazdani42/nvim-tree.lua/issues/1094#issuecomment-1076328060 . That will rule out a problem specific to your machine, versus a problem with your nvim-tree setup.

**Comment by Samyak2** [comment] 2022-03-30 05:27
I updated nvim-tree again and removed `auto_close` as per the warning. Without making any other changes (https://github.com/Samyak2/nvim-config/commit/1565cc949124534f55a50bb4eb6a18305425907a), the issue with `actions.open_file.quit_on_open` was fixed :)

Not sure what happened there, but if I get time I'll try to reproduce it with the minimal config

**Comment by BitInByte** [comment] 2022-03-30 22:00
Found out the issue in my side and it was conflict in my config, thanks for all the suggestions and all the support :)

**Comment by alex-courtis** [comment] 2022-03-30 23:11
It looks like everyone here has a working configuration now.

@anurag3301 it looks like you have a working minimal configuration; we will leave it to you to add the rest of your nvim configuration.

**Comment by anurag3301** [comment] 2022-03-31 15:07
@alex-courtis yeah I am clear on my end, you can close it. I'll try to rectify the conflict when I get some free time.

**Comment by alex-courtis** [comment] 2022-03-31 23:50
Closing. Please do open a new bug report if you experience problems in the future.

**Closed by alex-courtis** 2022-03-31 23:50 UTC
Labels: question

**Comment by gokberkgunes** [comment] 2022-04-15 23:48
Greetings, this issue along with settings are not being applied is possibly caused by a single line. For those who have a similar issue remove the config line that is shown below from your package manager configuration file.

```
use {
    'kyazdani42/nvim-tree.lua',
    requires = {
      'kyazdani42/nvim-web-devicons', -- optional, for file icon
    },
-    config = function() require'nvim-tree'.setup {} end
}
```

**Comment by alex-courtis** [comment] 2022-04-16 01:24
> Greetings, this issue along with settings are not being applied is possibly caused by a single extra line suggested in the main page.

Great find - many thanks!

Updating README now.

**Comment by anurag3301** [comment] 2022-04-16 03:01
Thanks, @gokberkgunes, it worked finally :)
