### ISSUE TITLE
Filter exclude does not take into account gitignored files

### ISSUE THREAD

**Issue by good-idea** [kyazdani42/nvim-tree.lua#892] opened 2022-01-12 03:04 UTC
Is it possible to whitelist a file that is otherwise ignored, via `.gitignore` files or otherwise?

I imagine my use case is a common one -- I've ignored my `.env` files, but need to edit them frequently that I'd like them to show up in the explorer.

I thought this might do the trick:

```
  filters = {
    custom = {
      ".git",
      "!.env"
    }
  },
 ```

 but no dice.

**Comment by kaykhancheckpoint** [comment] 2022-01-31 09:29
did you ever find a solution for this?

**Comment by kyazdani42** [comment] 2022-02-01 08:18
```
- |filters.exclude|: list of directories or files to exclude from filtering
    (will always be shown)
      type: `{string}`
      default: `{}`
```
reopen if you cannot make it work.

**Comment by kaykhancheckpoint** [comment] 2022-02-01 11:17
Did not work for me, trying to exclude .env because i want to view/edit that file

```
  filters = {
      dotfiles = false,
      custom = {'node_modules', '.cache'},
      exclude = {'.env'}
  },
  ```

**Comment by kyazdani42** [comment] 2022-02-02 08:19
you are right, the current code does not allow excluding the gitignored files. Not sure if this is a bug or if this was intended by the original author. I'll change the title a bit.

**Comment by strdr4605** [comment] 2022-02-28 09:53
Any progress on this?

I would like to do

```lua
  filters = {
      exclude = { 'node_modules' },
  },
```

**Comment by kyazdani42** [comment] 2022-02-28 20:47
no progress yet, i didn't have time to work on this :) I have very few bugs left to fix, this might be fixed in the next weeks.

**Closed** 2022-03-06 13:16 UTC
Labels: bug
