### ISSUE TITLE
Feature: Fold all folders

### ISSUE THREAD

**Issue by yassinebridi** [kyazdani42/nvim-tree.lua#602] opened 2021-08-30 14:56 UTC
Is it possible to have a keybinding to fold all folders at once, as coc-explorer does:

https://user-images.githubusercontent.com/18403595/131359234-f3430c1c-4ac2-44ba-a48f-85f43bb03c67.mov

**Comment by kyazdani42** [comment] 2021-08-30 16:56
duplicate of #435 closing in favor of this one :)

**Closed by kyazdani42** 2021-08-30 16:56 UTC
