### ISSUE TITLE
Allow multiple nvim-trees to be opened with their own state

### ISSUE THREAD

**Issue by hgiesel** [kyazdani42/nvim-tree.lua#1353] opened 2022-06-15 23:44 UTC
**Is your feature request related to a problem? Please describe.**

For better support of vinegar mode, nvim-tree should be able to have multiple file explorers open at the same time with their own state respectively. At the moment this will case a lot of unexpected behavior, like nvim-tree becoming unresponsive. 

**Describe the solution you'd like**
You should be able to open nvim-tree in two separate panes, and operate them individually.
Alternatively, `:vsplit` in an nvim-tree window, should leave the user with two independent file explorers.

**Describe alternatives you've considered**
This problem only arises if you try to use nvim-tree in _vinegar mode_ (also called split browser). When using it as a project drawer, you will never get in the situation of having two nvim-tree instances at once.

**Additional context**
Related: #1065

**Comment by alex-courtis** [comment] 2022-06-18 01:27
duplicate of #457

**Closed by alex-courtis** 2022-06-18 01:27 UTC
Labels: feature request
