### ISSUE TITLE
LuaTreeFindFile doesn't always work

### ISSUE THREAD

**Issue by Akin909** [kyazdani42/nvim-tree.lua#10] opened 2020-05-18 14:52 UTC
Thanks for fixing #9 so quickly :raised_hands: .

I ran into another issue FYI :sweat_smile:, when buffers from different repositories are open, nvim-tree doesn't move to the current project root (or alternatively the directory that contains the file). The GIF below hopefully shows what I mean. The first buffer in the GIF is my dotfiles repo, but I opened vim in a dart project repo. LuaTree sticks to the initial directory, and when I move into the dotfiles project it doesn't change the tree to show the new dir.

![tree-find-file](https://user-images.githubusercontent.com/22454918/82226279-3544ee80-991e-11ea-8860-bc940dbe4b86.gif)

Note: using `LuaTreeFindFile` in a buffer in a different project than lua tree does nothing

Still reading through the code so not exactly sure what is going on yet. Looks like maybe `ROOT_PATH` isn't being updated when you enter a new dir :man_shrugging:

**Comment by Akin909** [comment] 2020-05-18 14:57
If you point me in the right direction I can take a look if that would help? Might take me a bit to figure out how it works first

**Comment by kyazdani42** [comment] 2020-05-18 15:40
Thanks for making so detailed issues :) 
Well i can take a look, the code is a little bit nasty imo so it might be easier for me to fix this !

**Comment by kyazdani42** [comment] 2020-05-18 15:53
i hate lua regex matching.
If it's not fixed on your end, reopen this

**Comment by Akin909** [comment] 2020-05-18 16:45
Thanks for the quick PR @kyazdani42 just tested it locally and seems to still be happening

**Comment by kyazdani42** [comment] 2020-05-18 16:57
mmh strange i cannot reproduce the issue anymore.
Well if you want to take a look at the `find_file` function in `lua/lib/state.lua`, your issue should be located around 
```lua
if node.relpath and relpath:find(utils.path_to_matching_str(node.relpath)) then
```
where relpath is the relative path of the node, and path_to_matching_str a function replacing `-` and `.` characters with `%-` and `%.` for lua to match paths properly in string:find.
The function itself is a bit clunky, but the only part that failed me a few times is this if condition.

**Comment by kyazdani42** [comment] 2020-05-18 17:00
Are you running macos or linux ?

**Comment by Akin909** [comment] 2020-05-18 17:06
> Are you running macos or linux ?

I'm on Ubuntu 20.04

It looks like lua tree uses the dir that vim was opened from and sticks with that regardless of what buffer you are in, not sure if that is the intended behaviour?

My assumption was that if I opened vim in say `~/myproject/` it would change the lua tree dir depending on the buffer I was editing. In my case I navigated to `~/.dotfiles/vim/init.vim` so I expected the root dir would change to either be `~/.dotfiles` since it is a repo but granted doing project dirs is maybe an extra feature, then maybe the root dir would be `~/.dotfiles/vim` but the lua tree stays in `~/myproject/stuff.dart`.

**Comment by Akin909** [comment] 2020-05-18 17:07
Alternatively maybe lua tree should just follow vim's dir and then users can use settings like `autochdir` or plugins like `vim-rooter` :shrug:

**Comment by kyazdani42** [comment] 2020-05-18 17:29
So it is a different kind of issue, indeed this plugin uses the default dir where it was opened.
I stick with that because sometimes i'm in a project, and i want to open the tree in a subdirectory (and i dont want the tree to go to the root of the project).
I could add an option for that though, should be simple to fix.

Also multiple projects is a feature i didn't think about, but it would be quite hard to implement in the current state, it would require a different implementation.
I was thinking of doing a big refactoring soon, to make the code better and the plugin more stable, and i'd also like to use vim nightly features (because its much more convenient).
I might add the feature to the refactoring if i find a proper way to implement it.

**Comment by Akin909** [comment] 2020-05-18 17:35
One way that I've seen this solved is in `defx` you can pass an argument to the launch command like `LuaTree --path=("user_finds_path")` maybe that's a cheaper way to solve the problem or maybe it's just as complex, not sure

**Comment by kyazdani42** [comment] 2020-05-18 17:36
well i prefer classic `g:` options, its easier to manage in my opinion

**Comment by kyazdani42** [comment] 2020-05-18 17:48
Actually, if you open neovim with `nvim` and not `nvim .` it will follow user options. This is a little akward to handle because i could say `open tree depending on neovim default dir`, but what if a user does `nvim ~/some_folder` and is in a different place in the system ? it would still open in the place he opens vim.
What i should do is run an autocmd when vim updates the directory, but it would break the way lua tree is currently working :/

**Comment by kyazdani42** [comment] 2020-05-18 17:57
oh my bad i just realized i didn't understand your issue at all. I'm gonna fix this asap sorry !

**Comment by kyazdani42** [comment] 2020-05-18 18:02
it's fixed, i will add support for multiple workspaces one day, thanks for the tip ;)

**Closed** 2020-05-18 18:02 UTC

**Comment by Akin909** [comment] 2020-05-18 21:11
Ah I actually didn't really mean more than one workspace tbh, although if you mean like vscode that might be cool. I basically just meant when you open Lua Tree in a buffer the root directory should be the one of the current buffer. I tried master but it didn't resolve it unfortunately. I made a PR #13 which works for me locally. Let me know what you think :+1:
