### ISSUE TITLE
update_focused_file not working on first nvim-tree toggle

### ISSUE THREAD

**Issue by devdeadly** [kyazdani42/nvim-tree.lua#1003] opened 2022-02-19 09:38 UTC
**OS**
Operation system's name and version
```
                    'c.          colby@colby.local
                 ,xNMM.          -----------------
               .OMMMMo           OS: macOS 12.1 21C52 arm64
               OMMM0,            Host: MacBookPro18,1
     .;loddo:' loolloddol;.      Kernel: 21.2.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 2 hours, 39 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 70 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1920x1080, 1920x1080
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: HackNerdFontCompleteM-Regular 20
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Apple M1 Pro
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Apple M1 Pro
       .cooc,.    .,coo:.        Memory: 2091MiB / 16384MiB
```
**Neovim version**
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
```

**Nvim-tree version**
master branch

**Describe the bug**
**When first launching nvim**, nvim-tree will only `update_focused_file` if I close nvim-tree and re-open it, or if once opened, I navigate back to the open buffer. Instead, it always opens at the root directory to begin with.

**To Reproduce**
Explained above

**Expected behavior**
The current file is always focused.

https://user-images.githubusercontent.com/21346716/154795392-d1f08151-8c7a-4445-a02a-6ded887fb529.mov

```
return function()
  local nvim_tree = require 'nvim-tree'
  local map = require('nvim-tree.config').nvim_tree_callback

  nvim_tree.setup {
    auto_close = true,
    disable_netrw = true,
    update_focused_file = {
      enable = true,
    },
    diagnostics = {
      enable = true,
    },
    hijack_cursor = true,
    view = {
      auto_resize = true,
      mappings = {
        list = {
          { key = '<C-R>', cb = map 'refresh' },
          { key = 'a', cb = map 'create' },
          { key = 'd', cb = map 'remove' },
          { key = 'h', cb = map 'close_node' },
          { key = 'I', cb = map 'toggle_ignored' },
          { key = 'l', cb = map 'edit' },
          { key = 'r', cb = map 'rename' },
          { key = 's', cb = map 'split' },
          { key = 'v', cb = map 'vsplit' },
          { key = 'Y', cb = map 'copy_path' },
          { key = 'y', cb = map 'copy_name' },
        },
        custom_only = false, -- false means the list above will merge with defaults
      },
    },
    actions = {
      open_file = {
        quit_on_open = true,
      },
    },
  }
end
```

**Comment by gegoune** [comment] 2022-02-19 10:03
Are you using ahmedkhalf/project.nvim or something similar by any chance?

**Comment by devdeadly** [comment] 2022-02-19 14:23
@gegoune I am not!

**Comment by kyazdani42** [comment] 2022-02-19 15:57
Hum, could not reproduce. Might be conflicting with another plugin i suppose, can you try disabling all plugins but nvim-tree ? If it does not happen then could you try to identify the plugin that causes the conflict ?

**Comment by devdeadly** [comment] 2022-02-20 07:35
Triple checked and confirmed it still happens when nvim-tree is the only plugin. Furthermore, I was able to find what commit the bug was introduced. Let it be known I was also seeing weirdness with my custom mappings not working on this commit, though that seemed intermittent, so not sure what was going on there.

Again, the main error I'm seeing is I'm having to open nvim tree for the first time (cursor is not on the focused file, nor is that folder open). But if I close and reopen nvim tree, the folder is open and _sometimes_ the file is highlighted.

#6da74679449897dd95eaecaefe8dea80fc7eb3de -- first bad commit
#3f4ed9b6c2598ab8304186486a05ae7a328b8d49 -- last good commit

**Comment by kyazdani42** [comment] 2022-02-20 09:54
@devdeadly cb is deprecated now in the mappings, you should use `action` (see help doc or readme for reference).
I can definitely not reproduce though. Your nvim-tree version does not seem up to date because i can reproduce with the bad commit but not on latest master.

**Comment by devdeadly** [comment] 2022-02-20 20:08
So weird. I have no idea what's going on then. I just pulled down master and now this is what I'm seeing. I've tried uninstalling the plugin and re-installing it. I wonder if there's anything else I can do 🤔 I'm curious if others are experiencing similar issues. I'm gonna clone my dotfiles on another computer and see if I still see the issue.

https://user-images.githubusercontent.com/21346716/154862143-768ead8a-232c-44ab-913a-3c7c40f85dd4.mov

**Comment by abulwafa** [comment] 2022-02-20 20:12
Same here, I temporarily  reverted back to "ec7043"

**Comment by devdeadly** [comment] 2022-02-20 20:22
> Same here, I temporarily reverted back to "ec7043"

Thanks for chiming in! Always comforting when you realize the bug isn't just on your machine lol. I just cloned my setup on another machine and saw the same issue as well.

**Comment by kyazdani42** [comment] 2022-02-20 20:50
my bad i introduced quite a bug :smile: it's fixed, startup should work as expected now.

**Comment by devdeadly** [comment] 2022-02-20 21:03
@kyazdani42 thanks for the quick turnaround!

However, I'm still having to open, close, and reoopen the file tree for it to find the focused file

https://user-images.githubusercontent.com/21346716/154864245-a3c08f5d-0ac5-490e-8d2c-25a9d557cdb5.mov

**Comment by abulwafa** [comment] 2022-02-20 21:11
> my bad i introduced quite a bug 😄 it's fixed, startup should work as expected now.

Confirmed , Thank you 😀

**Comment by devdeadly** [comment] 2022-02-20 21:12
@abulwafa do you also see what I'm seeing in my last screen recording?

**Comment by abulwafa** [comment] 2022-02-20 21:13
> 

Do you lazy load using the "cmd" directive ?

**Comment by kyazdani42** [comment] 2022-02-20 21:13
i can finally reproduce this consistently. No worries, the explorer is not properly loaded before the find-file runs.

**Comment by abulwafa** [comment] 2022-02-20 21:15
> i can finally reproduce this consistently. No worries, the explorer is not properly loaded before the find-file runs.

@kyazdani42 I only have this issue if I lazyload NvimTree upon "NvimTreeToggle" cmd

**Comment by kyazdani42** [comment] 2022-02-20 21:17
Try in a git project i think you'll reproduce this (it only happens during startup before opening for the first time)

**Comment by abulwafa** [comment] 2022-02-20 21:18
> Try in a git project i think you'll reproduce this (it only happens during startup before opening for the first time)

@kyazdani42 confirmed !

**Comment by kyazdani42** [comment] 2022-02-20 21:20
should be fixed, can you confirm ?

**Closed** 2022-02-20 21:20 UTC

**Comment by abulwafa** [comment] 2022-02-20 21:25
> should be fixed, can you confirm ?

@kyazdani42 wow that was fast 😄, confirmed with and without lazy loading

**Comment by devdeadly** [comment] 2022-02-20 21:41
@kyazdani42 you nailed it! thanks for the crazy response time! 

sponsoring 💜
