### ISSUE TITLE
Add option to put files first and then folders afterwards

### ISSUE THREAD

**Issue by th4s** [kyazdani42/nvim-tree.lua#1525] opened 2022-08-20 14:14 UTC
Is there an option to make nvim-tree list files first? Currently it puts files after folders. I would like to invert that.

**Comment by gegoune** [comment] 2022-08-20 15:31
That is savage. :) 
Never thought anyone would like that kind of sorting. Apologies for response that being nothing into conversation, just felt like I need to express how surprised I was when reading this feature request. :)

**Comment by th4s** [comment] 2022-08-20 15:53
No problem, I mainly use neovim for Rust programming, and I find it much more clear to directly see the `mod.rs` file of a module instead of searching it somewhere after 20 folders ^^

**Comment by alex-courtis** [comment] 2022-08-21 00:14
Useful

Duplicate of #1490

**Closed by alex-courtis** 2022-08-21 00:14 UTC
Labels: feature request
