### ISSUE TITLE
Files inside directory not intended

### ISSUE THREAD

**Issue by meain** [kyazdani42/nvim-tree.lua#1] opened 2020-03-04 10:46 UTC
![screenshot](https://i.imgur.com/vFf2wJs.png)

If you see, the files inside lib is rendered along with lib.
I think this might only happens without icons, not sure though.

**Comment by kyazdani42** [comment] 2020-03-04 11:50
i'm gonna take a look, formatting might be badly handled without the vim-devicons package

**Comment by kyazdani42** [comment] 2020-03-04 12:23
I cannot reproduce, can you specify your environment ? (os, terminal, $TERM variable)

**Comment by meain** [comment] 2020-03-04 12:45
OS: macOS 10.13.6
terminal: alacritty
TERM: screen256-color
tmux: 3.0a
nvim: v0.5.0-36d1335

**Comment by kyazdani42** [comment] 2020-03-04 13:05
i use alacritty with tmux on linux. When i tested on macos with tmux and iterm it worked fine too.
Maybe your font is the culprit, i'll try something that don't support unicode and see if it happens.
Which font did you specify in your alacritty.yml ?

**Comment by meain** [comment] 2020-03-04 13:19
I was using `CamingoCode`. I tried it out with other fonts too.
I don't think it is because of the font because it works fine for folders.

Also I tried it with a font that has some icons, and it seems that only folders have icons assigned. I do not have `WebDevIconsGetFileTypeSymbol` thought. This is just my font icons, I think. If you see, there is nothing that gets displayed for files, only for folders. Maybe something related to that?

![](https://i.imgur.com/Pue7FGd.png)

**Comment by meain** [comment] 2020-03-04 13:28
It seems to work fine with this, but the git highlight for files is broken

```diff
diff --git a/lua/lib/format.lua b/lua/lib/format.lua
index 9bf5ddb..7588d2f 100644
--- a/lua/lib/format.lua
+++ b/lua/lib/format.lua
@@ -19,7 +19,7 @@ local function default_icons(_, isdir, open)
         return " "
     end
 
-    return ""
+    return "  "
 end
 
 local function create_matcher(arr)
```

**Comment by kyazdani42** [comment] 2020-03-04 13:30
Hum yes i tried to find a font that doesn't display folders but i didn't find one. Its because i display folders without the `WebDevIconsGetFileTypeSymbol` so if your font doesnt have it it might cause weird stuff.
The issue is that these icons takes 3/4 bytes so the UI highlighting is a little hard to do dynamically. 
Would making an option for displaying glyphs would solve this ?

**Comment by meain** [comment] 2020-03-04 13:35
Yeah, I guess having an option to disable glyphs should work.

**Comment by kyazdani42** [comment] 2020-03-04 13:50
ok it's fixed now.
You should be able to specify `g:lua_tree_show_folders=0` and `g:lua_tree_show_git_icons=0`

**Closed by kyazdani42** 2020-03-04 13:50 UTC

**Comment by meain** [comment] 2020-03-04 13:59
Cool, that works. Thanks for the plugin btw.

**Comment by meain** [comment] 2020-03-04 14:01
Coo, that seems to work. Thanks for the plugin!

**Comment by meain** [comment] 2020-03-04 14:02
I think something like `lua_tree_show_icons` or `lua_tree_show_glyphs` might be a better a name for the variable.

**Comment by kyazdani42** [comment] 2020-03-04 16:44
I'll think about a proper way to do this. Specifying an object should be more appropriate
