### ISSUE TITLE
Error while making any file 

### ISSUE THREAD

**Issue by Iamafnan** [kyazdani42/nvim-tree.lua#835] opened 2021-12-09 14:50 UTC
**OS**
Android 10

**Neovim version**
NVIM V0.7.0-dev

**Nvim-tree version**
Master branch

**Describe the bug**
Getting error while making file

**To Reproduce**
Press `a` and add a file name

**Expected behavior**
The should be added to the directory

**Screenshot**
![IMG_20211209_201032](https://user-images.githubusercontent.com/80388154/145418376-2f52326d-f787-4cc7-ba1a-57c29aea9245.jpg)

**Comment by CanKolay5677** [comment] 2021-12-09 15:10
https://github.com/kyazdani42/nvim-tree.lua/issues/769#issue-1046484403

**Comment by CanKolay5677** [comment] 2021-12-09 15:10
#769

**Comment by CanKolay5677** [comment] 2021-12-10 13:44
How you can installed neovim 0.7? I trying to compile but it gives errors.

**Comment by Iamafnan** [comment] 2021-12-10 14:56
I have added a new repository which provides NVIM 0.7.0-dev

**Comment by CanKolay5677** [comment] 2021-12-10 15:13
How?

**Comment by Iamafnan** [comment] 2021-12-10 17:14
See this repo https://github.com/MrAdityaAlok/mradityaalok.github.io

**Comment by kyazdani42** [comment] 2021-12-12 11:35
duplicate of #769 , closing this one :)

**Closed by kyazdani42** 2021-12-12 11:35 UTC
