### ISSUE TITLE
lib.lua[273]:Failed to rename buffer

### ISSUE THREAD

**Issue by greister** [kyazdani42/nvim-tree.lua#215] opened 2021-02-25 01:54 UTC
After pull the new commit.
got the error:lib.lua[273]:Failed to rename buffer.

**Comment by curtainp** [comment] 2021-02-25 03:14
i have the same problem

**Comment by osa1** [comment] 2021-02-25 07:07
This is introduced with 905afba. Parent commit of that one works fine (491fd68).

**Comment by kyazdani42** [comment] 2021-02-25 08:46
Hi, I need more information, I havent encountered that issue.

**Comment by kyazdani42** [comment] 2021-02-25 08:52
I think this is a duplicate of #213 please refer to the docs in the meanwhile.

**Comment by ray-x** [comment] 2021-02-26 01:03
It seems that `g:nvim_tree_bindings` is no longer needed.  Remove this setting and should works.

**Comment by kyazdani42** [comment] 2021-02-26 22:12
nvim_tree_bindings is still required if you wish to add new bindings to the tree buffer or you want to override existing ones.

**Comment by koopa1338** [comment] 2021-03-05 22:05
Its pretty verbose to override keybindings, it would be much easier if the plugin would export the the `get_lua_cb` function, maybe with a better name. This is how remapping looks before and after:

 ```diff
--- old.lua
+++ new.lua
vim.g.nvim_tree_bindings = {
-    cd = {'.'},
-    rename = {'c'},
-    copy = {'y'},
-    prev_git_item = {'gn'},
-    next_git_item = {'gp'},
}

vim.g.nvim_tree_bindings = {
+    ["."] = ":lua require'nvim-tree'.on_keypress('cd')<CR>",
+    ["c"] = ":lua require'nvim-tree'.on_keypress('rename')<CR>",
+    ["y"] = ":lua require'nvim-tree'.on_keypress('copy')<CR>",
+    ["gn"] = ":lua require'nvim-tree'.on_keypress('next_git_item')<CR>",
+    ["gp"] = ":lua require'nvim-tree'.on_keypress('prev_git_item')<CR>",
}

```

**Comment by kyazdani42** [comment] 2021-03-06 11:38
you are right, i'll push something today to fix these issues.

**Comment by kyazdani42** [comment] 2021-03-06 11:51
fixed in 58e44d29

**Closed by kyazdani42** 2021-03-06 11:51 UTC
