### ISSUE TITLE
Bug: `find_file` not cleaning previous position rendering

### ISSUE THREAD

**Issue by mr-celo** [kyazdani42/nvim-tree.lua#915] opened 2022-01-25 16:11 UTC
First of all, great plugin! I love. Coming from NERDTree and this feels so great!
Just to make it even better, I'm reporting this

**OS**
MacOS Monterey 12.1

**Neovim version**
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.6.1/share/nvim"
```

**Nvim-tree version**
`2dfed89af7724f9e71d2fdbe3cde791a93e9b9e0`

**Describe the bug**
When buffers change, the tree fails to clear the rendering of the previous buffer. And it accumulates "active" buffer lines.

https://user-images.githubusercontent.com/97023211/151014435-c049c4c3-d4f1-48da-a2fe-c07385d2d5cb.mov

**To Reproduce**
Enable `update_cqd`. E.g.:
```lua
vim.g.nvim_tree_respect_buf_cwd = 1

require('nvim-tree').setup({
  update_cwd = true,
  update_focused_file = {
    enable = true,
    update_cwd = true,
  },
})
```

**Expected behavior**
Only the open buffer line should be selected.

**Comment by kyazdani42** [comment] 2022-02-03 12:21
I wasn't able to reproduce this. Not sure why this happens, looks like a neovim issue to me, because cursorline cannot have multiple lines. Or maybe this is related to something else.

**Comment by kyazdani42** [comment] 2022-02-06 18:33
I've seen this yesterday once, but i think this might be caused by neovim. Looks strange to me that the cursorline would be duplicated, because setting the cursor should only be highlighting one line.
Closing this because i'm 99% sure it's upstream :smile:

**Closed by kyazdani42** 2022-02-06 18:33 UTC
