### ISSUE TITLE
NvimTree not showing any files or folders under the cwd

### ISSUE THREAD

**Issue by augustocdias** [kyazdani42/nvim-tree.lua#1383] opened 2022-06-29 10:37 UTC
### Description

When I open NvimTree I see nothing 
![image](https://user-images.githubusercontent.com/1080789/176416186-ed7a3cee-5ed5-4458-8cfe-d4458e537724.png)

### Neovim version

```text
NVIM v0.8.0-dev+514-g21a1f1f55
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOs 12.4 running on M1

### nvim-tree version

7285898

### Minimal config

```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
    require('packer').startup({
        {
            'wbthomason/packer.nvim',
            {
                'kyazdani42/nvim-tree.lua',
                requires = {
                    'kyazdani42/nvim-web-devicons', -- optional, for file icons
                },
            },
        },
        config = {
            package_root = package_root,
            compile_path = install_path .. '/plugin/packer_compiled.lua',
            display = { non_interactive = true },
        },
    })
end

_G.load_config = function()
    require('nvim-tree').setup({
        diagnostics = {
            enable = true,
        },
        git = {
            enable = true,
        },
        filters = {
            custom = { '.rbc$', '~$', '.pyc$', '.db$', '.sqlite$', '__pycache__', '.git', '.cache' },
        },
        renderer = {
            indent_markers = {
                enable = true,
            },
            highlight_git = true,
            highlight_opened_files = '3',
            group_empty = true,
        },
        actions = {
            open_file = {
                quit_on_open = true,
                window_picker = {
                    enable = false,
                    exclude = {
                        filetype = { 'notify', 'packer', 'qf' },
                        buftype = { 'terminal' },
                    },
                },
            },
        },
    })
    print('Config finished')
end
if vim.fn.isdirectory(install_path) == 0 then
    print('Installing Telescope and dependencies.')
    vim.fn.system({ 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path })
end
load_plugins()
require('packer').sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

### Steps to reproduce

1. nvim -nu minimal.lua
2. Run command NvimTreeOpen

### Actual behavior

![image](https://user-images.githubusercontent.com/1080789/176415904-bcba559a-1de9-4162-af43-85dc2555b8da.png)

**Comment by kyazdani42** [comment] 2022-07-02 10:12
could not reproduce, could you try setting `set shell=bash` and see if this still happens ?

**Comment by alex-courtis** [comment] 2022-07-02 23:39
> It seems the issue is with the `filters` option. As soon as I remove it, it works

You could remove filters one by one to see which one is the problem.

**Comment by kyazdani42** [comment] 2022-07-03 09:53
I've tried reproducing with this config, and it does not filter out everything though.

**Comment by augustocdias** [comment] 2022-07-06 06:29
@kyazdani42 I tried with bash. Same issue. I realised that the responsible filter for the issue is the `~$`. Without it it works. 

This has been there for so long that I don't even remember why it is there. It was working fine with it before though. Feel free to close if you want.

**Comment by kyazdani42** [comment] 2022-07-06 09:04
i'd like to understand why the `~$` would filter everything, but i'm closing anyway :)

**Closed by kyazdani42** 2022-07-06 09:04 UTC
Labels: bug, awaiting feedback
