### ISSUE TITLE
Show git icons in files to the right as folders

### ISSUE THREAD

**Issue by stsewd** [kyazdani42/nvim-tree.lua#72] opened 2020-08-02 17:05 UTC
![Screenshot from 2020-08-02 12-02-31](https://user-images.githubusercontent.com/4975310/89128024-11725d00-d4b8-11ea-88ea-5cb334439f17.png)

Folders show the git icon to the right, I'd like to do the same for files. I don't think there is a way to do that right now, so it would be a new setting

**Comment by kyazdani42** [comment] 2020-08-02 17:19
there is a PR that will be merged soon.

**Comment by kyazdani42** [comment] 2020-08-02 17:19
duplicate of #65

**Comment by kyazdani42** [comment] 2020-08-03 08:16
i think i was wrong, the PR will only align icons to the left an not the right. If this is enough for you just close this, otherwise we'll make a PR to address this issue when we have some time.

**Comment by alex-courtis** [comment] 2022-04-03 05:59
Following request in #246

**Closed by alex-courtis** 2022-04-03 05:59 UTC
Labels: feature request
