### ISSUE TITLE
Ignore dirs and files from `.gitignore`

### ISSUE THREAD

**Issue by UltiRequiem** [kyazdani42/nvim-tree.lua#1032] opened 2022-02-28 22:56 UTC
Previously this was done automatically, I think, but now it doesn't. 

The option was changed or right now is not implemented?

**Comment by alex-courtis** [comment] 2022-02-28 23:07
This is still functional, and default behaviour. It may be disabled via [git.ignore](https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L283)

What does your setup look like? Could you post your
```lua
require'nvim-tree'.setup {
	...
}
```

What other plugins are running?

**Comment by UltiRequiem** [comment] 2022-03-01 00:30
> What does your setup look like? 

```lua
vim.g.nvim_tree_indent_markers = 1
vim.g.nvim_tree_root_folder_modifier = ':~'
vim.g.vim_tree_tab_open = 1
vim.g.nvim_tree_width_allow_resize = 1
vim.g.nvim_tree_git_hl = 1
vim.g.nvim_tree_highlight_opened_files = 1
vim.g.nvim_tree_add_trailing = 0
vim.g.nvim_tree_group_empty = 0
vim.g.nvim_tree_disable_window_picker = 1
vim.g.nvim_tree_icon_padding = ' '

vim.g.nvim_tree_icons = {
  default = '',
  symlink = '',
  git = {
    unstaged = '✗',
    staged = '✓',
    unmerged = '',
    renamed = '➜',
    untracked = '★',
    deleted = '',
    ignored = '◌',
  },
  folder = {
    default = '',
    open = '',
    arrow_open = '',
    arrow_closed = '',
    empty = ' ',
    empty_open = ' ',
    symlink = '',
    symlink_open = '',
  },
  lsp = { hint = ' ', info = ' ', warning = ' ', error = ' ' },
}

require('nvim-tree').setup({
  disable_netrw = true,
  hijack_netrw = true,

  diagnostics = {
    enable = false,
    icons = {
      hint = '',
      info = '',
      warning = '',
      error = '',
    },
  },

  update_focused_file = {
    enable = true,
    update_cwd = false,
    ignore_list = {},
  },

  filters = {
    dotfiles = false,
    custom = { '.git' },
  },

  view = {
    width = 35,
    side = 'right',
    auto_resize = false,
    mappings = {
      custom_only = false,
      list = {},
    },
  },
})

vim.cmd('highlight NvimTreeFolderIcon guibg=blue')
```

https://github.com/UltiRequiem/UltiVim/blob/main/plugin/nvim-tree.lua



> What other plugins are running?

I'm using telescope, tressiter, bufferline, packer, lualine, gitsings, dahsboard.nvim and coc.nvim 😆

**Comment by alex-courtis** [comment] 2022-03-01 00:41
My setup is non-defaults only: https://github.com/alex-courtis/arch/blob/master/config/nvim/lua/nvt.lua

However, I tested .gitignore with a bare minimal setup: no plugins other than:
```vim
	Plugin 'kyazdani42/nvim-tree.lua'
	Plugin 'kyazdani42/nvim-web-devicons'
```

and a "nothing" nvim-tree setup:
```lua
require'nvim-tree'.setup {
}
```

Please try that and see whether .gitignore is working for you.

Note that a proper "minimal setup" for bug reports may come soon: https://github.com/kyazdani42/nvim-tree.lua/issues/1033

**Comment by UltiRequiem** [comment] 2022-03-01 00:45
I copy-paste your config, result 👇🏽 

![image](https://user-images.githubusercontent.com/71897736/156083123-c65513dd-7e3e-4975-acb6-948ba7f32089.png)

This makes me think is not my config...

My nvim info

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

**Comment by alex-courtis** [comment] 2022-03-01 00:58
I have cloned your repo, touched .pnpm-debug.log and run with my full setup and the nothing setup. The log is correctly hidden.

It could be another plugin, or it could perhaps be something in your ~/.gitconfig or ~/.gitignore

Here's a "nothing" init.vim, which assumes vundle is system installed. Substitute your package manage as needed:
```vim
filetype off
call vundle#begin("~/.local/share/nvim/vundle")
Plugin 'kyazdani42/nvim-tree.lua'
Plugin 'kyazdani42/nvim-web-devicons'
call vundle#end()

nmap	<silent>	<Leader>a	:NvimTreeOpen<CR>

lua require'nvim-tree'.setup {}
```

**Comment by UltiRequiem** [comment] 2022-03-01 01:25
My `~/.gitconfig` just includes my user and I don't have the other file.

I move all my files from my plugin dir and only left the nvim tree one (and the  one of mappings 😆), but the issue persists 😔 

![image](https://user-images.githubusercontent.com/71897736/156086940-9156daba-7752-4780-81b1-b33b2c29c624.png)

No Idea what could be the problem, I will install neovim from git now, maybe the problem is the version...

**Comment by UltiRequiem** [comment] 2022-03-01 01:30
So I reinstall neovim(from git)

```
NVIM v0.7.0-dev+1159-gcf0266fae
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/z/.cache/yay/neovim-git/src/build/config -I/home/z/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/z/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/z/.cache/yay/neovim-git/src/build/include
Compiled by z

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

Same problem 😞 

![image](https://user-images.githubusercontent.com/71897736/156087559-462a1eeb-e787-476d-bf18-70c732449bf9.png)

**Comment by alex-courtis** [comment] 2022-03-01 01:41
Looking at the above screenshot, I cannot see any files that should be .gitignored - no logs are not shown.

filters.dotfiles is true, so the dotfiles should be visible.

Which version of nvim-tree are you running? `git log --format="%h" -n 1`
3d8912c is latest. Update if you are behind and try again.
There has been some work recently around git ignored files. Perhaps it is a bug/side effect that has already been resolved.

**Comment by UltiRequiem** [comment] 2022-03-01 01:44
> Looking at the above screenshot, I cannot see any files that should be .gitignored - no logs are not shown.

`node_modules` and `.next` should be ignored

```
# dependencies
/node_modules
/.pnp
.pnp.js

.yarn/*
!.yarn/patches
!.yarn/releases
!.yarn/plugins
!.yarn/sdks
!.yarn/versions
.pnp.*

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env.local
.env.development.local
.env.test.local
.env.production.local

# vercel
.vercel

# typescript
*.tsbuildinfo
```

https://github.com/UltiRequiem/ultirequiem.com/blob/main/.gitignore

> There has been some work recently around git ignored files. Perhaps it is a bug/side effect that has already been resolved.

The latest one, just updated

**Comment by alex-courtis** [comment] 2022-03-01 02:01
Ah I see... different repo ;) I have cloned that one but cannot reproduce. node_modules and .next are hidden. If I remove those lines from .gitignore and write, they immediately appear.

Last question, that should have been asked first: which OS and which git are you using? I am running vanilla Arch with mainline git 2.35.1 / nvim 0.6.1 2.1.0-beta3 / luajit 2.1.0-beta3

A last step: attempt to replicate on a VM with a boring Linux install, such an Ubuntu.

Hopefully someone can replicate this, as I am out of ideas.

**Comment by UltiRequiem** [comment] 2022-03-01 03:12
> Last question, that should have been asked first: which OS and which git are you using? I am running vanilla Arch with mainline git 2.35.1 / nvim 0.6.1 2.1.0-beta3 / luajit 2.1.0-beta3

I'm using Arch too, btw ™️ 

![image](https://user-images.githubusercontent.com/71897736/156097576-3228d690-278d-4be3-b6dd-025e89857f1a.png)

Git

![image](https://user-images.githubusercontent.com/71897736/156097791-feba9031-db47-4d5c-8d94-082cb2631f82.png)


> A last step: attempt to replicate on a VM with a boring Linux install, such an Ubuntu.

I will try tomorrow is sleep time for me

![gn gif](https://c.tenor.com/Hfu-VJ4gjVwAAAAC/mmi-morsmutual.gif)

**Comment by kyazdani42** [comment] 2022-03-01 19:15
hi ! Are you sure you haven't committed the ignored files before writing the .gitignore ? What happens if you do this in a fresh repo without staging anything ?

**Comment by UltiRequiem** [comment] 2022-03-01 19:23
> hi ! Are you sure you haven't committed the ignored files before writing the .gitignore? What happens if you do this in a fresh repo without staging anything?

Hum, so I deleted a repo and recloned it from GitHub, and now works 🤯 

To add more context, I format my PC yesterday, I have two disks, one where I leave all the important stuff and the other for the OS.

So I just erased the one that had the OS information and left the one with all my git repositories as normal, so the same `node_modules`, `.git`, etc remain even after formatting the system.

I think that's the unique thing I could say to justify this behavior 😔 

I think this case will be pretty unique, so I proceed to close the issue, thanks for the help!

**Comment by UltiRequiem** [comment] 2022-03-01 19:44
the issue persists, I forgot to reinstall the dependencies that's why the dependencies directories didn't appear 😭 

After installing and building

![image](https://user-images.githubusercontent.com/71897736/156237491-e73d2909-87d8-484d-91d1-e94291f02d98.png)

gitignore 

```
node_modules/
docs/
lib/
```
Again no Idea what the problem is.

**Comment by kyazdani42** [comment] 2022-03-01 20:06
what does `git status --porcelain=v1 --ignored=matching` return ?

**Comment by UltiRequiem** [comment] 2022-03-01 20:23
> git status --porcelain=v1 --ignored=matching

![image](https://user-images.githubusercontent.com/71897736/156243156-c345d386-2725-46e5-a1ce-3ee25c07845b.png)

**Comment by kyazdani42** [comment] 2022-03-01 21:26
that's very strange, i pretty much no ideas to be honest. Can you add the git configuration in the setup to make sure everything is declared as you expect ? And increase the timeout value maybe ?

**Comment by alex-courtis** [comment] 2022-03-02 00:25
Timeout may be useful. I eagerly await results.

Without a reproducible test case, I'm not seeing many other options besides adding some debug. Here's a little file logger function I sometimes use: https://github.com/alex-courtis/arch/blob/master/config/nvim/lua/amc.lua#L3

**Comment by UltiRequiem** [comment] 2022-03-02 01:13
> that's very strange, i pretty much no ideas to be honest. Can you add the git configuration in the setup to make sure everything is declared as you expect ? And increase the timeout value maybe ?

How can I increase the timeout value? Will try about the git config on the setup

**Comment by alex-courtis** [comment] 2022-03-02 01:16
Increase the [git.timeout](https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L290) setting. :crossed_fingers:

**Comment by UltiRequiem** [comment] 2022-03-02 01:34
> How can I increase the timeout value? Will try about the git config on the setup

Still the same 😔 

![image](https://user-images.githubusercontent.com/71897736/156277399-a093a05c-268b-4074-ac72-3740bb781dbc.png)

New config:

```lua
require'nvim-tree'.setup {
  git = {
    enable = true,
    ignore = true,
    timeout = 1000,
  }
}
```

I don't it helps by I'm installing it like this

```lua
require('packer').startup(function(use)
  -- Packer Itself
  use('wbthomason/packer.nvim')

--....
  -- UI Plugins
  use('glepnir/dashboard-nvim')
  use('nvim-lualine/lualine.nvim')
  use('p00f/nvim-ts-rainbow')
  use('akinsho/nvim-bufferline.lua')
  use({
    'kyazdani42/nvim-tree.lua',
    requires = { 'kyazdani42/nvim-web-devicons' },
  })

 -- .....
end)
```

**Comment by UltiRequiem** [comment] 2022-03-02 01:35
> Timeout may be useful. I eagerly await results.
> 
> Without a reproducible test case, I'm not seeing many other options besides adding some debug. Here's a little file logger function I sometimes use: https://github.com/alex-courtis/arch/blob/master/config/nvim/lua/amc.lua#L3

How can I use that function?

Ahh, long time without having problems with my (n)vim configurations...

**Comment by alex-courtis** [comment] 2022-03-02 02:31
Put the file in `~/.config/nvim/lua`. You could then instrument and log `runner.lua` via something like:
```lua
function Runner:_getopts(stdout_handle)
  local untracked = self.list_untracked and '-u' or nil
  local ignored = (self.list_untracked and self.list_ignored) and '--ignored=matching' or '--ignored=no'
  local opts = {
    args = {"--no-optional-locks", "status", "--porcelain=v1", ignored, untracked},
    cwd = self.project_root,
    stdio = { nil, stdout_handle, nil },
  }
  require'amc'.log("_getopts returning " .. vim.inspect(opts))
  return opts
end
```
Running that git command manually might reveal something interesting.

You could also put some logs in and around `Runner:_run_git_job` to see if the job is finishing etc.

Disclaimer: this is the first time I have looked at that area of the nvim-tree codebase; the above may be misinformed and incorrect.

**Comment by kyazdani42** [comment] 2022-03-02 07:44
@UltiRequiem did you modify the git config for your repo to not show the untracked files ?

**Comment by RMTT** [comment] 2022-03-10 03:19
I reproduce it via create a folder with different uid and gid from current user under a git repo.

**Comment by alex-courtis** [comment] 2022-03-10 06:08
[Diagnostic Logging](https://github.com/kyazdani42/nvim-tree.lua#diagnostic-logging) has been added.

Please update to latest and set [log.enable](https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L471) and `log.types.git`.

This will show what we are asking git, and git's responses.

**Comment by kyazdani42** [comment] 2022-03-18 10:22
Please follow what alex-courtis said, and give some feedback :)

**Comment by UltiRequiem** [comment] 2022-04-03 18:18
> Please follow what alex-courtis said, and give some feedback :)

Hey sorry for the late response, I lost the notification.

I changed my computer a few days ago and I no longer can reproduce this issue.

**Comment by UltiRequiem** [comment] 2022-04-03 18:19
> I reproduce it via create a folder with different uid and gid from current user under a git repo.

That makes sense, the repos I was operating were on a directory on a disk which a different UID than my user one.

**Comment by alex-courtis** [comment] 2022-04-03 23:39
> directory on a disk which a different UID

We can try replicating that again. Seeing the logs, with the git response would still be helpful.

**Comment by alex-courtis** [comment] 2022-04-16 03:51
> That makes sense, the repos I was operating were on a directory on a disk which a different UID than my user one.

> I reproduce it via create a folder with different uid and gid from current user under a git repo.

I am still not able to reproduce, with files/directories from a different user/group. Those files are readable and directories executable by the user, so that they are visible to git / nvim / nvim-tree.lua.

Without further information we cannot progress this issue.

Please enable [logging](https://github.com/kyazdani42/nvim-tree.lua#diagnostic-logging) with `log.types.git` so that we may see what git is seeing.

**Comment by delfick** [comment] 2022-04-30 00:13
I have the same problem after a :PlugUpdate

<details>
<summary>bare_init.vim</summary>

```
call plug#begin('~/.config/vim/plugged')

Plug 'kyazdani42/nvim-tree.lua'

call plug#end()

let g:nvim_tree_git_hl = 1
let g:nvim_tree_highlight_opened_files = 1

:lua << EOF

require'nvim-tree'.setup {
  disable_netrw = false,
  git = {
    enable = true,
    ignore = true,
    timeout = 400,
  },
  filters = {
    exclude = { ".pytest_cache", "__pycache__", ".runner", "runner.egg-info" }
  },
  log = {
    enable = true,
    truncate = true,
    types = {
      git = true,
      profile = true,
    },
  },
}
EOF

nnoremap <C-e> :NvimTreeToggle<CR>

```
</details>

<details>
<summary>nvim --version</summary>

```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```
</details>

On Mac OS Monterey 12.3 (2020 M1 Macbook pro)

![Screen Shot 2022-04-30 at 10 10 00 am](https://user-images.githubusercontent.com/109301/166082548-fc70af7e-44e0-46c1-8840-edd02393112b.png)

<details>
<summary>~/.cache/nvim/nvim-tree.log</summary>

```
[2022-04-30 10:09:39] [profile] START git job /Users/stephenm/Projects/pc-internal/bex-dev-setup
[2022-04-30 10:09:39] [git] running job with timeout 400ms
[2022-04-30 10:09:39] [git] git --no-optional-locks status --porcelain=v1 --ignored=matching -u
!! .dmypy.json
!! .mypy_cache/.gitignore
!! .mypy_cache/3.10/
!! .mypy_cache/CACHEDIR.TAG
!! .pytest_cache/.gitignore
!! .pytest_cache/CACHEDIR.TAG
!! .pytest_cache/README.md
!! .pytest_cache/v/
!! runner/.mypy_cache/.gitignore
!! runner/.mypy_cache/3.10/
!! runner/.mypy_cache/CACHEDIR.TAG
!! runner/.runner/
!! runner/.tests/
!! runner/runner.egg-info/
!! runner/runner/__pycache__/
!! runner/runner/helpers/__pycache__/
!! runner/runner/operations/__pycache__/
!! runner/runner/operations/dns/__pycache__/
!! runner/runner/operations/status/__pycache__/
!! runner/runner/runtime/__pycache__/
!! runner/runner/runtime/repositories/__pycache__/
!! runner/runner/runtime/setup/__pycache__/
!! runner/runner/runtime/setup/registered/__pycache__/
!! runner/runner/ui/__pycache__/
!! runner/runner/vendor/__pycache__/
!! runner/runner/vendor/ptterm/__pycache__/
!! runner/runner/vendor/ptterm/backends/__pycache__/
!! runner/tools/.noy_black/
!! runner_out.log
[2022-04-30 10:09:39] [profile] END   git job /Users/stephenm/Projects/pc-internal/bex-dev-setup  12ms
[2022-04-30 10:09:39] [git] job success
[2022-04-30 10:09:39] [profile] START draw
[2022-04-30 10:09:39] [profile] END   draw  1ms
[2022-04-30 10:09:39] [profile] START draw
[2022-04-30 10:09:39] [profile] END   draw  1ms
```
</details>

**Comment by delfick** [comment] 2022-04-30 00:16
though, annoyingly I thought to remove those filters after I made a post. I had those as `ignore` in the setup function and when I opened vim it said ignore wasn't an option and that was the closest I could see to be relevant. It seems git files are ignored if I don't have that line....

**Comment by alex-courtis** [comment] 2022-04-30 00:42
> It seems git files are ignored if I don't have

That's working as intended: those are excluded from ignoring:
```
  - |filters.exclude|: list of directories or files to exclude from filtering: always show them.
    Overrides `git.ignore`, `filters.dotfiles` and `filters.custom`.
```

To explicitly ignore files, you'll need to use `filters.custom`.

**Comment by alex-courtis** [comment] 2022-04-30 00:43
Please reopen if you have any further questions.

**Closed by alex-courtis** 2022-04-30 00:43 UTC
Labels: bug, not answered, awaiting feedback
