### ISSUE TITLE
Using nvim-tree.lua in combination with ntpeters/vim-better-whitespace causes whitespaces to be highlighted in insert mode

### ISSUE THREAD

**Issue by xfzv** [kyazdani42/nvim-tree.lua#592] opened 2021-08-26 15:54 UTC
For some reasons, if using nvim-tree.lua in combination with [ntpeters/vim-better-whitespace](https://github.com/ntpeters/vim-better-whitespace), the whitespaces are highlighted while being in insert mode, which isn't supposed to happen. Disabling nvim-tree.lua fixes the issue.

Simple `init.vim` to reproduce the issue (I'm loading the two plugins with [vim-plug](https://github.com/junegunn/vim-plug))

I used a markdown file for the demonstration but it occurs with any filetype (conf, html, json,sh...)

```vim
call plug#begin("~/.config/nvim/plugged")
Plug 'ntpeters/vim-better-whitespace'
Plug 'kyazdani42/nvim-tree.lua'
call plug#end()
 
autocmd FileType markdown EnableWhitespace
```

![01](https://user-images.githubusercontent.com/78810647/130994214-75a625d3-ccfe-4259-ba0e-ac898598072c.png)

---

After disabling nvim-tree.lua

```vim
call plug#begin("~/.config/nvim/plugged")
Plug 'ntpeters/vim-better-whitespace'
"Plug 'kyazdani42/nvim-tree.lua'
call plug#end()
 
autocmd FileType markdown EnableWhitespace
```

![02](https://user-images.githubusercontent.com/78810647/130994303-9037a144-15cd-45b4-a243-2cffee785b38.png)

Any idea? 

Thanks!

**Comment by kyazdani42** [comment] 2021-08-28 12:05
hi ! I'm really not sure why this happens, nvim-tree window settings should not affect others.
But isn't the purpose of the plugin to show the red sign for empty space ?

**Comment by xfzv** [comment] 2021-08-28 16:39
> hi ! I'm really not sure why this happens, nvim-tree window settings should not affect others.

Indeed, that's very strange. I stripped down the init.vim file as much as possible to make sure that was not because of another setting.

> But isn't the purpose of the plugin to show the red sign for empty space ?

It is, except in insert mode: the whitespaces in the current line shouldn't be highlighted in red. This is what happens when nvim-tree is enabled too: as soon as you press the space key, the previous character is highlighted in red.

I wonder if some other users can reproduce the issue.

**Comment by CT-66** [comment] 2021-09-23 11:07
I too have this same issue. Except for me, the auto trimming of whitespaces on save is not working. The whitespaces are highlighted though. When I removed nvim-tree.lua from my init.vim, the better-whitespace plugin seems to work normally.

**Comment by xfzv** [comment] 2021-09-23 16:21
> I too have this same issue. Except for me, the auto trimming of whitespaces on save is not working. The whitespaces are highlighted though. When I removed nvim-tree.lua from my init.vim, the better-whitespace plugin seems to work normally.

Can confirm the auto trimming of whitespaces on save isn't working for me either if I have nvim-tree.lua enabled. Works fine with the latter disabled.

**Comment by CT-66** [comment] 2021-09-26 04:26
Its kind of weird that nvim-tree affects the functioning of vim-better-whitespace. I guess I have to go back to nerdtree until this is issue is fixed.

**Comment by kyazdani42** [comment] 2021-09-26 09:47
wasn't able to reproduce. The whitespaces are properly highlighted, when in insert mode, they properly disappear and it does not strip whitespace on save either with nvim-tree enabled and disabled. Would you mind sharing some of your config @CT-66  ?

**Comment by CT-66** [comment] 2021-09-27 10:50
Here's a stripped down version of my config:

```
" better-whitespace
let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1
let g:better_whitespace_guicolor='darkred'
let g:strip_whitespace_confirm=0
let g:strip_whitelines_at_eof=1
let g:better_whitespace_filetypes_blacklist=[]


" nvim-tree
let g:nvim_tree_side = 'left'
let g:nvim_tree_ignore = [ '.git', 'node_modules', '.cache', '__pycache__'  ]
nnoremap <C-n> :NvimTreeToggle<CR>
```


> it does not strip whitespace on save either    

Add `let g:strip_whitespace_on_save=1` to your init.vim to strip whitespace on save.

**Comment by kyazdani42** [comment] 2021-10-03 11:18
works like a charm for me. I definitely cannot reproduce everything is working as expected. Maybe latest days fixes and refactors affected this in some way ? could you confirm this still happens on latest master ?

**Comment by xfzv** [comment] 2021-10-03 22:55
Looks like the issue is gone on my end after recent updates, hopefully that's the case for @CT-66 as well.

**Comment by CT-66** [comment] 2021-10-04 14:22
Thank you, it indeed works like a charm now. @xfzv I think you can close the issue now, if it works fine for you.

**Comment by xfzv** [comment] 2022-02-12 14:53
Reopening because I'm having the issue again since the last few days.

- `~/.config/nvim/init.vim`:

```vim
call plug#begin("~/.config/nvim/plugged")
Plug 'ntpeters/vim-better-whitespace'
Plug 'kyazdani42/nvim-tree.lua'
call plug#end()
 
autocmd FileType markdown EnableWhitespace
lua require('_nvim-tree')
```

- `~/.config/nvim/lua/_nvim-tree.lua`:

```lua
require'nvim-tree'.setup {
    disable_netrw       = true,
}
```

I found two workarounds:
1. Commenting `lua require('_nvim-tree')` in `init.vim`.
2. Commenting the whole `_nvim-tree.lua` content. Interestingly, only commenting everything in the `require'nvim-tree'.setup{ } section` isn't enough, I do have to comment `require'nvim-tree'.setup {` and the closing bracket too, either the issue is still occurring. I tried with different options instead of `disable_netrw` and could reproduce every time.

Any idea?

**Comment by xfzv** [comment] 2022-02-12 15:05
I noticed something else. If I first run [vim-startify](https://github.com/mhinz/vim-startify) and open a new or existing file, all good. However, if I open Neovim from my terminal with `nvim`, the issue occurs for both new and existing files. I tried with an empty `.zshrc` file and two different terminals apps (konsole and alacritty) but it doesn't make any difference, the issue persists.

**Closed** 2022-02-14 18:16 UTC
