### ISSUE TITLE
Unknow option warning

### ISSUE THREAD

**Issue by aspeddro** [kyazdani42/nvim-tree.lua#1194] opened 2022-04-24 12:23 UTC
### Description

After 5bbd3a0a917122b9330dab10b55bb56cc18c9a3d, nvim-tree show warning for valid options

![image](https://user-images.githubusercontent.com/16160544/164976220-cbabf086-d92d-48ea-a675-59062879a862.png)

### Neovim version

```markdown
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Linux arch 5.17.3-arch1-1

### nvim-tree version

5bbd3a0

### Steps to reproduce

1. Open nvim

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

**Comment by kyazdani42** [comment] 2022-04-24 12:39
cannot reproduce, can you send a minimal configuration please ?

**Comment by gegoune** [comment] 2022-04-24 14:50
@kyazdani42 I am sorry ;)

**Comment by kyazdani42** [comment] 2022-04-24 19:26
@gegoune why :) ?

**Comment by gegoune** [comment] 2022-04-24 19:27
> @gegoune why :) ?

It was meant to reduce issues but instead brought couple on day 1. :)

**Comment by kyazdani42** [comment] 2022-04-24 19:29
haha no worries, we'll make it work ! I actually found issues in my own config thanks to this

**Comment by alex-courtis** [comment] 2022-04-25 00:05
#1166 #1195

**Comment by alex-courtis** [comment] 2022-04-25 00:20
Thank you for reporting this one. It is a case that was missed during testing. The change has been reverted - please update the plugin.

**Comment by alex-courtis** [comment] 2022-04-25 03:10
This has been fixed in a new PR https://github.com/kyazdani42/nvim-tree.lua/pull/1195

I'd be very grateful if you could test the branch `#1166-validate-config` @aspeddro

**Comment by aspeddro** [comment] 2022-04-25 04:08
Fixed @alex-courtis.

**Closed** 2022-04-25 04:08 UTC
Labels: bug
