### ISSUE TITLE
[question] .git folder icon

### ISSUE THREAD

**Issue by CleoMenezes** [kyazdani42/nvim-tree.lua#928] opened 2022-02-03 14:50 UTC
Is there any way to make the .git folder have a different icon?
   
```
    \ 'folder': {
    \   'git': "",
    \   'arrow_open': "",
    \   'arrow_closed': "",
    \   'default': "",
    \   'open': "",
    \   'empty': "",
    \   'empty_open': "",
    \   'symlink': "",
    \   'symlink_open': "",
    \   }
```

_BTW, it would be interesting to have it by default._

**Comment by kyazdani42** [comment] 2022-02-05 11:16
`:help nvim-tree-highlight`
```
NvimTreeGitDirty
NvimTreeGitStaged
NvimTreeGitMerge
NvimTreeGitRenamed
NvimTreeGitNew
NvimTreeGitDeleted
```
you could just `:hi` them

**Comment by kyazdani42** [comment] 2022-02-05 11:17
This is a duplicate of #902, closing :)

**Closed by kyazdani42** 2022-02-05 11:17 UTC
