### ISSUE TITLE
Lsp_diagnostics not working, or at least not displaying signs 

### ISSUE THREAD

**Issue by lucipher128** [kyazdani42/nvim-tree.lua#717] opened 2021-10-13 07:30 UTC
I have everything set up properly, yet i can't see any lsp diagnostics icon when i purposely trigger an error in a file in the current workspace, the lsp server responds to the request as expected.
`diagnostics.enable` is set to true and 
`use {
 'kyazdani42/nvim-tree.lua',
        requires = 'kyazdani42/nvim-web-devicons', 
        config = function() require'nvim-tree'.setup() end
}`
is how i load the plugin/initialize it.

function `diagnostics.update()` seems to never get called :/ i just can't find out what is going on.

thx for your time and for the plugin, its really great !

**Comment by kyazdani42** [comment] 2021-10-16 16:17
```lua
use { 'kyazdani42/nvim-tree.lua', requires = 'kyazdani42/nvim-web-devicons', config = function() require'nvim-tree'.setup { diagnostics = { enable = true } } end }
```

**Comment by baleksa** [comment] 2022-01-08 10:56
Same here. I set diagnostics inside setup function, both with pacher and later in init.lua. Tried configurations tested to work on other pcs.
```lua
 use {
    'kyazdani42/nvim-tree.lua', -- A File Explorer For Neovim Written In Lua
    requires = {
      'kyazdani42/nvim-web-devicons', -- optional, for file icon
    },
    config = function() require'nvim-tree'.setup { diagnostics = { enable = true } } end
  }
```
```lua
local tree_cb = require'nvim-tree.config'.nvim_tree_callback
require'nvim-tree'.setup { -- Setup nvim file explorer written in Lua
  view = {
    mappings = {
      custom_only = false,
      list = {
        { key = { "l", "<CR>", "o" }, cb = tree_cb("edit")},
        { key = "h", cb = tree_cb("close_node") },
        { key = "v", cb = tree_cb("vsplit") },
      },
    },
  },
  auto_close = true,
  -- diagnostics = {
  --   enable = true,
  --   icons = { error = "", warn = "", hint = "", info = "", },
  -- },
 diagnostics = {
    enable = false,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    }
  },
  update_focused_file = {
    enable = true,
    update_cwd = true,
    ignore_list = {},
  },
  update_cwd = true,
  update_to_buf_dir = {
    enable = true,
    auto_open = true,
  },
}

```

**Comment by diegoroccia** [comment] 2022-01-15 21:50
I have the same problem. I have the diagnostics setup config as suggested @kyazdani42 

```
    use({
        "kyazdani42/nvim-tree.lua",
        requires = {
            "kyazdani42/nvim-web-devicons",
        },
        config = function()
            require("nvim-tree").setup({
                auto_close = true,
                open_on_tab = true,
                hijack_cursor = true,
                update_cwd = true,
                diagnostics = {
                    enable = true,
                    show_on_dirs = true,
                    icons = {
                        hint = "",
                        info = "",
                        warning = "",
                        error = "",
                    },
                },
                update_focused_file = {
                    enable = true,
                    update_cwd = true,
                    ignore_list = {},
                },
                filters = {
                    dotfiles = false,
                },
                view = {
                    width = 30,
                    height = 30,
                    hide_root_folder = false,
                    side = "left",
                    auto_resize = true,
                },
            })
        end,
    })
```

**Comment by kyazdani42** [comment] 2022-01-21 11:43
cannot reproduce, check that your lsp is working as expected and you have the signcolumn enabled.
Closing this, seems to be a user related config issue.

**Closed by kyazdani42** 2022-01-21 11:43 UTC
