### ISSUE TITLE
[bug] render bug

### ISSUE THREAD

**Issue by cossonleo** [kyazdani42/nvim-tree.lua#88] opened 2020-08-08 08:49 UTC
It get error when I open tree
E5108: Error executing lua .../.config/nvim/plugged/nvim-tree.lua/lua/lib/renderer.lua:271: Expected lua string

**Comment by kosayoda** [comment] 2020-08-08 09:46
Hello, I am getting this error too. May I know why you closed this issue?

**Comment by kyazdani42** [comment] 2020-08-10 16:32
not sure why this would happen, can i have more informations please ?

**Comment by braidn** [comment] 2020-08-10 20:59
@kyazdani42 seeing this as well. The steps for me to reproduce it are:

1. Open a directory using: `nv .`
1. Toggle nvim-tree.lua using 'LuaTreeToggle`
1. Sometimes just toggling the tree will throw the error or sometimes I need to:
1. Open a folder in the tree.

Hopefully this helps.

**Comment by kyazdani42** [comment] 2020-08-10 21:47
this doesn't help much, i'd need something like a minimal vimrc you can reproduce the error with, and a list of file maybe.

**Comment by braidn** [comment] 2020-08-10 22:40
>  i'd need something like a minimal vimrc you can reproduce the error with, and a list of filename maybe.

Sure! By list of filenames you mean included plugins?

**Comment by kyazdani42** [comment] 2020-08-11 11:04
Nope, the list of filenames from the folder where the bug arise.

**Comment by braidn** [comment] 2020-08-11 12:22
current vimrc: https://gist.github.com/braidn/a1a389377e81f4c8d86d97bfcf6d08c9

List of filenames and Folders from a directory:

app
bin
config
config.ru
db
development.env
docker-compose.yml
Dockerfile
docs
Gemfile
Gemfile.lock
log
ops
public
Rakefile
README.md
spec
test.env
tmp

**Comment by kyazdani42** [comment] 2020-08-11 15:07
this issue arise when you disable the folder icon. I'm going to look into this

**Comment by braidn** [comment] 2020-08-11 15:08
> this issue arise when you disable the folder icon. I'm going to look into this

Amazing! I actually never got the folder icon to show up quite correct. It's likely due to the font. Although it does work for some reason with file icons?

**Comment by kyazdani42** [comment] 2020-08-11 15:12
maybe your fonts don't display some icons. And some terminals have bad issues with font rendering.

**Closed** 2020-08-11 15:12 UTC
