### ISSUE TITLE
Weird offset in nvim-tree

### ISSUE THREAD

**Issue by tomaskallup** [kyazdani42/nvim-tree.lua#904] opened 2022-01-20 10:37 UTC
**OS**
Manjaro 5.15.12-1

**Neovim version**
NVIM v0.7.0-dev+717-gf37c5f180

**Nvim-tree version**
Currently on 0a2f6b0

**Describe the bug**
Nvim tree seems to get into a weird state where it has "offset", meaning I try to open a file and it opens file below it.
I've recorded this, as it seems to happen randomly.

The two files (`result-local.json` and `result-staging.json`) were created using terminal inside nvim. Nvim tree displays them, but seems to be offset by 2 (exactly the two new files) when trying to open something.

https://user-images.githubusercontent.com/26621166/150322276-a5803c3f-e50c-4559-b42e-5a77353d7b99.mp4

**To Reproduce**
This seems to happen randomly, from what I gather, creating files outside of nvim-tree (using terminal) can somehow cause this, even though the files are visible in nvim-tree.

**Expected behavior**
Nvim-tree should just open the file I have my cursor on.

**Comment by gegoune** [comment] 2022-01-20 11:04
Noticed that as well. Refreshing tree fixes misalignment. Couldn't exactly pinpoint to specific actions yet.

**Comment by kyazdani42** [comment] 2022-02-03 12:34
does this still happens ? I haven't been able to reproduce.

**Comment by dairyisscary** [comment] 2022-02-04 10:30
I have experienced this quite often too. I don't have reproduction steps either, but one additional note: I believe it started with 0.6.0 neovim, though I'm not 100% certain.

**Comment by YaQia** [comment] 2022-02-04 14:55
Yeah, I have had the same expierence from time to time. Sorry to say that I can't find the cause of it. It's hard to be reproduced for me. I'm using nvim-tree in LunarVim (or 0.7 nvim).

**Comment by kyazdani42** [comment] 2022-02-05 11:13
@YaQia the tree is not watching the filesystem (yet :smiley:), if i can reproduce this i'd might be able to fix it.

**Comment by alex-courtis** [comment] 2022-04-03 02:45
Please attempt to provide a reproducer using the minimal config as per the new bug report: https://github.com/kyazdani42/nvim-tree.lua/issues/new/choose

Add plugins / configuration if necessary to reproduce.

**Comment by kyazdani42** [comment] 2022-05-21 10:17
Closing since there are no news here. Please ping me if you still experience this.

**Closed by kyazdani42** 2022-05-21 10:17 UTC
Labels: bug, not answered, awaiting feedback
