### ISSUE TITLE
Git highlight doesn't work for subfolder content

### ISSUE THREAD

**Issue by GabMus** [kyazdani42/nvim-tree.lua#578] opened 2021-08-19 17:38 UTC
It should show the files inside the `src` subfolder in red, similarly to `meson.build` in the root of the project.

Here's a screenshot describing the problem:

![](https://user-images.githubusercontent.com/1358527/130116986-e322831b-2597-424b-9a2c-372a2b318665.png)

And [here's my config](https://gitlab.com/gabmus/mydotfiles/-/blob/stow/nvim/dot-config/nvim/lua/nvimtree_conf.lua) for good measure, maybe I missed something.

And thanks for the awesome plugin, keep it up!

**Comment by kyazdani42** [comment] 2021-08-21 10:16
thanks for the kind words :) this looks like a bug to me, i'll have a look at it when i have some time.

**Comment by excvai** [comment] 2022-01-07 20:23
I have the same problem.
Git highlighting only works at the root level
Tried minimal settings from repo with last updated nvim-tree but nothing changed (I use Windows btw)

**Comment by kyazdani42** [comment] 2022-02-05 11:32
Hi, is this still relevant ?

**Comment by excvai** [comment] 2022-02-05 13:11
@kyazdani42 Oh thanks, it's working fine now. The problem is gone

By the way, I switched from Windows to Linux(Arch) and this problem did not exist there at all, so it's not too relevant for me. But I think this fix will help other Windows users. So thanks for your work anyway

**Comment by kyazdani42** [comment] 2022-02-05 13:22
the windows issue has been fixed i think :) closing this then.

**Closed by kyazdani42** 2022-02-05 13:22 UTC
