### ISSUE TITLE
New files not in directory

### ISSUE THREAD

**Issue by sarahkittyy** [kyazdani42/nvim-tree.lua#932] opened 2022-02-05 21:04 UTC
**OS**
`Linux sarah-pc 5.10.43.3-microsoft-standard-WSL2 #1 SMP Wed Jun 16 23:47:55 UTC 2021 x86_64 GNU/Linux`

**Neovim version**
```
NVIM v0.7.0-dev+761-g0d7a97224
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/sbin/clang -DNVIM_TS_HAS_SET_MATCH_LIMIT -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/sarahkitty/neovim/build/config -I/home/sarahkitty/neovim/src -I/home/sarahkitty/neovim/.deps/usr/include -I/usr/include -I/home/sarahkitty/neovim/build/src/nvim/auto -I/home/sarahkitty/neovim/build/include
Compiled by sarahkitty@sarah-pc

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Nvim-tree version**
latest

**Describe the bug**
New files are not opened in the same working directory as the tree.

**To Reproduce**
Steps to reproduce the behavior

* `cd` into directory
* Hit enter on file (`edit_no_picker` action)
* Focus newly opened buffer
* `:pwd`
* The directory is where neovim started in, not the tree root (the folder we cd'd into)

**Expected behavior**

The directory should be the tree root.

**Comment by sarahkittyy** [comment] 2022-02-05 21:06
Also note that in my config i do have
```lua
actions = {
    change_dir = {
        global = true
    }
}
```

**Comment by sarahkittyy** [comment] 2022-02-05 21:18
I have solved this temporarily with

`autocmd Filetype NvimTree nmap <silent><buffer><leader>e e:exec ":cd " . getcwd()<cr>`

I thought this was supposed to be what `actions.change_dir.global` should do?

**Comment by kyazdani42** [comment] 2022-02-05 22:16
Hi !
I just tried to reproduce with all the given informations and it behave correctly :/
`change_dir.global` will only run `:cd` instead of `:lcd` thus the tree root should always be the same as nvim's root directory.
I'm not sure how to debug this, i do not run windows and this *might* be an issue with the WSL.

**Comment by alex-courtis** [comment] 2022-02-26 02:33
I can reproduce this, but only with `actions.change_dir.global` false.

**Comment by alex-courtis** [comment] 2022-02-26 03:06
Confirmed working as intended with global false and true, on Arch Linux.

Add these diagnostics to see what's going on:
```vim
autocmd DirChanged window echom "DirChanged window " . winnr() . " " . " " getcwd(winnr())
autocmd DirChanged global echom "DirChanged global " . getcwd()
```

When global you should see a single DirChanged global when you change nvim-tree's directory.

When not global you should see DirChanged global to nvim's current directory when entering the file's window, and DirChanged window when entering the nvim-tree window.

**Comment by alex-courtis** [comment] 2022-04-16 03:09
@sarahkittyy are you still experiencing this problem? What are the results of the event logging?

**Comment by kyazdani42** [comment] 2022-05-29 11:05
closing since no answer. Please comment here if this happens for you again.

**Closed by kyazdani42** 2022-05-29 11:05 UTC
Labels: bug, not answered, awaiting feedback
