### ISSUE TITLE
Is there a way to swap between drives in Windows 10?

### ISSUE THREAD

**Issue by ObsidianChickenz** [kyazdani42/nvim-tree.lua#852] opened 2021-12-19 18:35 UTC
Is there any way for me to switch between C:\ and D:\ within nvim-tree?

**Comment by kyazdani42** [comment] 2022-02-05 13:22
Hi, sorry for the late answer.
I think if you just `:cd D:\` it will do ?

**Comment by kyazdani42** [comment] 2022-02-21 23:01
closing since no news.

**Closed by kyazdani42** 2022-02-21 23:01 UTC

**Comment by fukwho** [comment] 2022-03-04 20:56
This should be reopened this still is a current issue. I have tried refreshing NvimTree, closing it and reopening but the `:cd D:\` command won't work.

**Comment by kyazdani42** [comment] 2022-03-06 10:34
Could you open a proper issue ? There is almost no description in there and really hard for anyone to reproduce this and the author did not give any news since december.
