### ISSUE TITLE
Open on setup not working

### ISSUE THREAD

**Issue by ManInTheSuit** [kyazdani42/nvim-tree.lua#775] opened 2021-11-07 18:04 UTC
[nvim-tree-cfg.txt](https://github.com/kyazdani42/nvim-tree.lua/files/7492817/nvim-tree-cfg.txt)
Open on setup is not working, but toggling e.g. "auto-close" changes behaviour as expected. 

Everything seems to be working correctly as I need it to, except this.

It works  when I open blank neovim file (```neovim``` in terminal), but not as expected (doesn't show the blank file)

**Comment by kyazdani42** [comment] 2021-11-27 12:43
i do not understand what does not work for you, please provide:
- operating system
- neovim version
- nvim-tree version
and better detail your issue, 'not working' is not something i can reproduce.

**Comment by ManInTheSuit** [comment] 2021-11-27 13:11
OS: Solus Budgie, latest update
Nvim v0.5.1
nvim-tree latest PlugInstall update

When I use the following settings:
`  open_on_setup       = true ` 
open_on_setup is not working as expected. 
What I expect:
Open neovim tree along the nvim editor window any time I open a file in nvim.
What happens:
1) When I open an existing file in neovim, tree is not present by default. [example](https://i.imgur.com/uC5GAcv.png)
2) When I open a blank file (nvim in terminal or launching nvim with a launcher), I nvim tree is the _only_ window that opens in the window. [example](https://i.imgur.com/Elijutr.png)

I have attached init and lsp-tree vim files
[nvim.zip](https://github.com/kyazdani42/nvim-tree.lua/files/7611752/nvim.zip)

**Comment by vladdoster** [comment] 2021-11-28 09:56
What you expect is not the behavior described in the documentation for the `open_on_setup` setting. 

There is a different setting that does what you want.

Read through this [document](https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt).

**Comment by kyazdani42** [comment] 2021-11-28 13:21
closing this, the intended behavior is unrelated to open_on_setup.

**Closed by kyazdani42** 2021-11-28 13:21 UTC

**Comment by ManInTheSuit** [comment] 2021-11-30 12:08
> What you expect is not the behavior described in the documentation for the `open_on_setup` setting and is not an issue with NvimTree.
> 
> ```lua
> *nvim-tree.open_on_setup*
> - |open_on_setup|: will automatically open the tree when running setup if current
>   buffer is a directory, is empty or is unnamed.
>   type: `boolean`
>   default: `false`
> ```
> 
> There is a different setting that does what you want.
> 
> Read through this [document](https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt).

I see that now, reading the doc.

But isn't then 

`update_to_buf_dir   = {
        enable = true,
        auto_open = true,
      },`

supposed to do it? For me, it isn't doing it.

**Comment by ColonelPhantom** [comment] 2022-02-11 02:12
> What you expect is not the behavior described in the documentation for the `open_on_setup` setting and is not an issue with NvimTree.
> 
> ```lua
> *nvim-tree.open_on_setup*
> - |open_on_setup|: will automatically open the tree when running setup if current
>   buffer is a directory, is empty or is unnamed.
>   type: `boolean`
>   default: `false`
> ```
> 
> There is a different setting that does what you want.
> 
> Read through this [document](https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt).

I desire the same behaviour, but have not been able to locate a setting that does what I want. It doesn't sound like @ManInTheSuit has been able to locate it either.

Perhaps this could be documented more clearly?

**Comment by kyazdani42** [comment] 2022-02-11 09:07
I agree some option names are not very good. I have plans to make the documentation better once i've done all the refactorings i have planned.
