### ISSUE TITLE
Operations on the file won't update/refresh the tree

### ISSUE THREAD

**Issue by pedropmedina** [kyazdani42/nvim-tree.lua#403] opened 2021-05-27 22:57 UTC
Ever since I last updated (Today) creating, renaming, refreshing, etc... won't have any effect on the tree. I have to restart nvim in order to see the changes!?

- nvim version:
NVIM v0.5.0-dev+1260-ga6504ec33
Build type: Release
LuaJIT 2.1.0-beta3

- Operating system
macOs BigSur 11.3

**Comment by kjelly** [comment] 2021-05-28 02:31
I have the same issue.

Linux, Ubuntu 20.04.2 LTS
nvim v0.5.0-dev+1327-gdc18c1e3e
nvim-tree.lua commit id: 23935ff0036e26dbfe14e6aee96a7653ee704336

**Comment by kyazdani42** [comment] 2021-05-28 07:08
I cannot reproduce with `NVIM v0.5.0-dev+1358-g192ea01ed`. Could you maybe provide a minimal sample config ?

**Comment by kjelly** [comment] 2021-05-28 09:57
My vim config

```
let mapleader = ";"
let maplocalleader = "\<space>"

set nocompatible              " be improved
filetype off                  " required before plugins

silent! call plug#begin('~/.config/nvim/plugged')
Plug 'https://github.com/kyazdani42/nvim-tree.lua'
call plug#end()
```

**Comment by pedropmedina** [comment] 2021-05-28 13:16
I just pull the latest update from neovim @kyazdani42. Also I forgot to mention I'm building nvim from source. Here's my [config](https://github.com/pedropmedina/dotfiles/tree/master/nvim)

**Comment by kjelly** [comment] 2021-05-28 13:22
After using the latest neovim, there is no issue now.

```
nvim --version
NVIM v0.5.0-dev+1358-g192ea01ed
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by pedropmedina** [comment] 2021-05-28 15:19
Updating nvim to the latest version fixed it @kjelly  @kyazdani42. Thanks.

**Comment by Pasqat** [comment] 2021-05-28 15:51
I had the same problem with dev+1262 and solved updating to the latest version

**Comment by toilethub** [comment] 2021-05-29 07:16
I had the same issue but updating nvim solved it too. Thank you!
```
$ nvim --version      
NVIM v0.5.0-dev+1358-g192ea01ed
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by kyazdani42** [comment] 2021-05-31 07:08
seems fixed then i'll close this.

**Closed by kyazdani42** 2021-05-31 07:08 UTC
