### ISSUE TITLE
NvimTreeFindFile can't find file

### ISSUE THREAD

**Issue by kuznetsss** [kyazdani42/nvim-tree.lua#460] opened 2021-06-18 16:24 UTC
`NvimTreeFindFile` cann't find file from a directory which is outside of current working directory.

For example for file structure:
```
.
├── one
│   └── first.txt
└── two
    └── second.txt
```
If I change directory to `one` and run `nvim first.txt` then inside nvim use command `:e ../two/second.txt` and then use `:NvimTreeFindFile` nvim-tree will be opened inside `one` directory.

**Comment by kyazdani42** [comment] 2021-06-28 18:17
duplicate of #240 and #141.
Closing this in favor of the other two

**Closed by kyazdani42** 2021-06-28 18:17 UTC

**Comment by alexesba** [comment] 2022-01-11 17:32
It seems the configuration has changed, now we need to enable it. as follow. 
```lua
require'nvim-tree'.setup {
  update_cwd          = true,
  update_focused_file = {
    enable      = true,
    update_cwd  = true,
    ignore_list = {}
  },
}
```
