### ISSUE TITLE
NvimTree content shifted left when toggled with no focus

### ISSUE THREAD

**Issue by Bekaboo** [kyazdani42/nvim-tree.lua#1063] opened 2022-03-10 15:07 UTC
### Description

When nvim-tree is toggled using `lua require('nvim-tree').toggle(false, true)` (that is, with no focus), contents in the nvim-tree window is shifted left if the cursor is at column >= 25.

### Neovim version

```markdown
NVIM v0.7.0-dev
```

### Operating system and version

wsl ubuntu 20.04

### nvim-tree version

2457e14

### Steps to reproduce

1. Install and set nvim-tree with default config
2. In normal mode, move cursor to column >= 25
3. Run `lua require('nvim-tree').toggle(false, true)`
4. You can see that contents in the nvim-tree window is shifted left by 1 column. If the cursor is at column 50, the contents are shifted totally beyond the screen and you can see nothing in the nvim-tree window.

### Expected behavior

Nvim-tree fixs the first letter in the first col of the window

### Actual behavior

col = 24
![image](https://user-images.githubusercontent.com/76579810/157690401-45f80479-77d6-4c75-9bf7-004f092a7ff4.png)

col = 25
![image](https://user-images.githubusercontent.com/76579810/157690450-ddd4dd1f-0a02-4260-b9cd-1195b5f6153d.png)

col = 50
![image](https://user-images.githubusercontent.com/76579810/157690595-40179efd-0651-4a7a-9fcd-0709c2c035e7.png)

col = 80
![image](https://user-images.githubusercontent.com/76579810/157690716-d9c3f6ec-aff3-47ed-b43f-49929d08c337.png)

### Minimal config

```Lua
default
```

**Comment by alex-courtis** [comment] 2022-03-13 02:06
It looks like the sign column in nvim-tree is missing when col < 25.

When running with minimal config or my config, the sign column is always present, regardless of cursor position in the other buffer. Setting `signcolumn = "no",` results in the sign column always absent.

It looks like you're not using the default configuration as you have some custimisations going on there around nvim_tree_indent_markers.

Please use the minimal configuration and attempt to reproduce or post your full configuration, without running any other plugins.

**Comment by Bekaboo** [comment] 2022-03-13 02:32
> It looks like the sign column in nvim-tree is missing when col < 25.
> 
> When running with minimal config or my config, the sign column is always present, regardless of cursor position in the other buffer. Setting `signcolumn = "no",` results in the sign column always absent.
> 
> It looks like you're not using the default configuration as you have some custimisations going on there around nvim_tree_indent_markers.
> 
> Please use the minimal configuration and attempt to reproduce or post your full configuration, without running any other plugins.

I did not take screenshots using default config, but I've tried removing all customs configs and the problem still exists.

Here's screenshots using default config:
![image](https://user-images.githubusercontent.com/76579810/158042218-7d1d653d-439a-4bc0-8cc0-016db414af53.png)

Did you try calling `toggle` with `no_focus = false`. Only when calling this function with `no_focus = false` will this problem occurs?
![image](https://user-images.githubusercontent.com/76579810/158042305-5223358d-024e-4cb4-b98d-1dece0ada2c7.png)

**Comment by alex-courtis** [comment] 2022-03-20 05:10
I have failed to reproduce with `NVIM v0.7.0-dev+1285-g54f15a9e4` (I was on the stable 0.6.1 release):
* Very small or large window
* From second tab
* After opening/closing nvim-tree
* With &number
* With view.number

Could you please experiment further:
* Stable nvim 0.6.1
* Without any tabs open
* On a non-windows machine, perhaps a boring linux vm like ubuntu

**Comment by lu5je0** [comment] 2022-04-08 04:18
same

**Comment by alex-courtis** [comment] 2022-04-09 06:48
> same

Which OS and neovim version are you using @lu5je0 ?

**Comment by lu5je0** [comment] 2022-04-09 07:03
> > same
> 
> Which OS and neovim version are you using @lu5je0 ?

macOS , NVIM v0.7.0-dev+1416-g012c05580

**Comment by alex-courtis** [comment] 2022-04-10 02:32
Thanks @lu5je0 

I have build and tested with `NVIM v0.7.0-dev+1416-g012c05580` however I still cannot replicate this with the minimal config.

Could you please try using stable neovim `v0.6.1`

**Comment by lu5je0** [comment] 2022-04-16 06:18
@alex-courtis Sorry for late reply.I cannot pinpoint it to a specific list of steps to reproduce, but i will try.

**Comment by alex-courtis** [comment] 2022-06-19 04:52
Closing due to inactivity.

**Closed by alex-courtis** 2022-06-19 04:52 UTC
Labels: bug, not answered, awaiting feedback
